HTML conversions [sometimes display errors](https://info.dev.arxiv.org/about/accessibility_html_error_messages.html) due to content that did not convert correctly from the source. This paper uses the following packages that are not yet supported by the HTML conversion tool. Feedback on these issues are not necessary; they are known and are being worked on.

- failed: mdframed

Authors: achieve the best HTML results from your LaTeX submissions by following these [best practices](https://info.arxiv.org/help/submit_latex_best_practices.html).

[License: CC BY 4.0  
许可证：CC BY 4.0](https://info.arxiv.org/help/license/index.html#licenses-available)

arXiv:2502.19187v2 [cs.CL] 06 May 2025  
arXiv:2502.19187v2 [cs.CL] 2025 年 5 月 6 日

\correspondingauthor  \通讯作者

mehrankazemi@google.com and baharef@google.com  
mehrankazemi@google.com 和 baharef@google.com

# BIG-Bench Extra Hard  BIG-Bench 超难版

Mehran KazemiGoogle DeepMindBahare FatemiGoogle ResearchHritik BansalGoogle DeepMindUCLAJohn PalowitchGoogle DeepMindChrysovalantis AnastasiouGoogle DeepMindSanket Vaibhav MehtaGoogle DeepMindLalit K. JainGoogle ResearchVirginia AgliettiGoogle DeepMindDisha JindalGoogle DeepMindPeter ChenGoogle DeepMindNishanth DikkalaGoogle ResearchGladys TyenGoogle DeepMindXin LiuGoogle ResearchUri ShalitGoogle DeepMindSilvia ChiappaGoogle DeepMindKate OlszewskaGoogle DeepMindYi TayGoogle DeepMindVinh Q. TranGoogle DeepMindQuoc V. LeGoogle DeepMindOrhan FiratGoogle DeepMind

###### Abstract  摘要

Large language models (LLMs) are increasingly deployed in everyday applications, demanding robust general reasoning capabilities and diverse reasoning skillset. However, current LLM reasoning benchmarks predominantly focus on mathematical and coding abilities, leaving a gap in evaluating broader reasoning proficiencies. One particular exception is the BIG-Bench dataset, which has served as a crucial benchmark for evaluating the general reasoning capabilities of LLMs, thanks to its diverse set of challenging tasks that allowed for a comprehensive assessment of general reasoning across various skills within a unified framework. However, recent advances in LLMs have led to saturation on BIG-Bench, and its harder version BIG-Bench Hard (BBH). State-of-the-art models achieve near-perfect scores on many tasks in BBH, thus diminishing its utility. To address this limitation, we introduce BIG-Bench Extra Hard (BBEH), a new benchmark designed to push the boundaries of LLM reasoning evaluation. BBEH replaces each task in BBH with a novel task that probes a similar reasoning capability but exhibits significantly increased difficulty. We evaluate various models on BBEH and observe a (harmonic) average accuracy of 9.8% for the best general-purpose model and 44.8% for the best reasoning-specialized model, indicating substantial room for improvement and highlighting the ongoing challenge of achieving robust general reasoning in LLMs. We release BBEH publicly at: [https://github.com/google-deepmind/bbeh](https://github.com/google-deepmind/bbeh).  
大型语言模型（LLMs）正日益广泛地应用于日常应用中，这要求其具备强大的通用推理能力和多样化的推理技能。然而，当前针对 LLM 推理能力的基准测试主要集中于数学和编程能力，在评估更广泛的推理熟练度方面存在空白。一个特别的例外是 BIG-Bench 数据集，它因其多样化的挑战性任务集合，能够在统一框架内对 LLMs 在各种技能上的通用推理能力进行全面评估，从而成为评估 LLMs 通用推理能力的关键基准。然而，LLMs 的最新进展导致其在 BIG-Bench 及其更难版本 BIG-Bench Hard（BBH）上的表现趋于饱和。最先进的模型在 BBH 的许多任务上取得了接近完美的分数，从而削弱了其实用性。为了解决这一局限性，我们引入了 BIG-Bench Extra Hard（BBEH），这是一个旨在突破 LLM 推理评估边界的新基准。BBEH 用新颖的任务替换了 BBH 中的每个任务，这些新任务探究相似的推理能力，但难度显著增加。 我们在 BBEH 上评估了多种模型，观察到最佳通用模型的（调和）平均准确率为 9.8%，而最佳推理专用模型的准确率为 44.8%，这表明仍有巨大的改进空间，并突显了在 LLMs 中实现稳健通用推理所面临的持续挑战。我们在以下地址公开发布了 BBEH：https://github.com/google-deepmind/bbeh。

## 1Introduction  1 引言

![Refer to caption](https://arxiv.org/html/2502.19187v2/x1.png)

Figure 1:Model performances on BBEH (harmonic mean over individual task performances).  
图 1：模型在 BBEH 上的表现（基于各任务表现的调和平均值）。

Recent research has made significant strides in evaluating the reasoning capabilities of large language models (LLMs), but the focus has been disproportionately skewed towards math/science and coding. This emphasis is likely driven by the availability of challenging benchmarks in these domains and the relative ease of evaluating quantitative solutions. However, reasoning encompasses a far broader spectrum of cognitive skills, including logical deduction, temporal and spatial understanding, commonsense reasoning, and even the ability to comprehend humor.††Llama and Qwen experiments in this paper were conducted only by parties outside of Google.  
本文中的 Llama 和 Qwen 实验仅由谷歌以外的机构进行。  
近期研究在评估大型语言模型（LLMs）的推理能力方面取得了显著进展，但关注点却不成比例地偏向数学/科学和编程领域。这种倾向很可能源于这些领域存在具有挑战性的基准测试，以及评估量化解决方案的相对便利性。然而，推理涵盖的认知技能范围要广泛得多，包括逻辑演绎、时空理解、常识推理，甚至理解幽默的能力。 †

To assess these diverse facets of reasoning, the community has relied on the BIG-Bench benchmark (Srivastava et al., [2022](https://arxiv.org/html/2502.19187v2#bib.bib45)), specifically its more challenging subset, BIG-Bench Hard (BBH) (Suzgun et al., [2022](https://arxiv.org/html/2502.19187v2#bib.bib46)). BBH has served as the de facto standard for evaluating general reasoning in LLMs due to its versatility and the wide array of reasoning skills it probes. However, the rapid advancements in LLM development has led to a saturation of BBH, with state-of-the-art models achieving over 90% accuracy. This performance ceiling renders BBH less effective in discriminating between the reasoning abilities of the latest generation of LLMs.  
为了评估这些多样化的推理能力，研究界一直依赖 BIG-Bench 基准测试（Srivastava 等人，2022），特别是其更具挑战性的子集 BIG-Bench Hard（BBH）（Suzgun 等人，2022）。BBH 因其多功能性以及所涵盖的广泛推理技能，已成为评估 LLM 通用推理能力的事实标准。然而，LLM 开发的快速进展导致 BBH 趋于饱和，最先进的模型已达到超过 90%的准确率。这一性能上限使得 BBH 在区分最新一代 LLM 的推理能力方面效果减弱。

To address this challenge and push the boundaries of LLM evaluation, we introduce BIG-Bench Extra Hard (BBEH), a new benchmark designed to assess advanced reasoning capabilities. BBEH builds upon BBH by replacing each of the 23 tasks from BBH with a novel counterpart that probes similar reasoning capabilities, but exhibits significantly increased difficulty. Solving the tasks in BBEH requires even further reasoning skills than the problems in BBH. These skills include, but are not limited to, many-hop reasoning, learning on the fly, finding errors in reasoning traces, processing long-context inputs and finding (multi-)needles in a haystack, going against strong prior, dealing with long-range dependencies, dealing with distractors and inducing patterns from examples. By presenting LLMs with problems that demand a wider array of reasoning capabilities, BBEH aims to provide a more accurate measure of their general reasoning abilities.  
为应对这一挑战并拓展 LLM 评估的边界，我们推出了 BIG-Bench Extra Hard（BBEH）——一个旨在评估高级推理能力的新基准。BBEH 在 BBH 的基础上，将其 23 项任务逐一替换为探究相似推理能力但难度显著提升的全新对应任务。解决 BBEH 中的任务需要比 BBH 问题更进一步的推理技能，这些技能包括但不限于：多跳推理、即时学习、发现推理轨迹中的错误、处理长上下文输入并寻找"大海捞针"（或多重线索）、突破强先验假设、处理长程依赖关系、应对干扰项以及从示例中归纳规律。通过向 LLM 呈现需要更广泛推理能力的问题，BBEH 旨在更准确地衡量其通用推理能力。

We provide a comprehensive evaluation of several state-of-the-art LLMs on BBEH. Our results demonstrate that BBEH presents a significant challenge even for the most advanced models. Specifically, we observe a ceiling accuracy of 23.9% for the best general-purpose model and 54.2% for the model reasoning-specialized model, highlighting the substantial headroom for improvement in robust general reasoning for LLM. Furthermore, we conduct a detailed failure analysis, revealing intriguing failure modes for both general-purpose LLMs and models specifically designed for reasoning and thinking. These findings offer valuable insights into the current limitations of LLMs and provide guidance for future research aimed at enhancing their reasoning capabilities.  
我们对多个最先进的 LLM 在 BBEH 上进行了全面评估。我们的结果表明，即使对于最先进的模型，BBEH 也构成了重大挑战。具体而言，我们观察到最佳通用模型的准确率上限为 23.9%，而专为推理设计的模型准确率上限为 54.2%，这突显了 LLM 在稳健通用推理方面仍有巨大的改进空间。此外，我们进行了详细的失败分析，揭示了通用 LLM 以及专门为推理和思考设计的模型都存在的有趣失败模式。这些发现为当前 LLM 的局限性提供了宝贵见解，并为未来旨在提升其推理能力的研究提供了指导。

## 2Related Work  2 相关工作

There has been significant emphasis on using LLMs for mathematical and scientific reasoning. This has led to the popularity and proliferation of math- and STEM-based evaluations, such as (Hendrycks et al., [2020](https://arxiv.org/html/2502.19187v2#bib.bib15); Cobbe et al., [2021](https://arxiv.org/html/2502.19187v2#bib.bib6)), and more recently, (Glazer et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib10); Phan et al., [2025](https://arxiv.org/html/2502.19187v2#bib.bib34)). However, the generalizability of mathematical reasoning skills to broader domains remains unclear. Indeed, attempts to make existing benchmarks more robust—for example, Mirzadeh et al. ([2024](https://arxiv.org/html/2502.19187v2#bib.bib30))—have highlighted an overall lack of robustness and logical reasoning capabilities. Several benchmarks have also been developed to address specific areas of reasoning, including temporal reasoning (Xiong et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib61); Beniwal et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib4); Dhingra et al., [2022](https://arxiv.org/html/2502.19187v2#bib.bib7)), spatial understanding (Bohnet et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib5); Yamada et al., [2023](https://arxiv.org/html/2502.19187v2#bib.bib62); Mirzaee et al., [2021](https://arxiv.org/html/2502.19187v2#bib.bib31); Shi et al., [2022](https://arxiv.org/html/2502.19187v2#bib.bib44)), commonsense reasoning (Zellers et al., [2019](https://arxiv.org/html/2502.19187v2#bib.bib65); Talmor et al., [2018](https://arxiv.org/html/2502.19187v2#bib.bib48); Sakaguchi et al., [2021](https://arxiv.org/html/2502.19187v2#bib.bib37)), and logical reasoning (Saparov and He, [2022](https://arxiv.org/html/2502.19187v2#bib.bib39); Tafjord et al., [2020](https://arxiv.org/html/2502.19187v2#bib.bib47); Saparov et al., [2023](https://arxiv.org/html/2502.19187v2#bib.bib40); Parmar et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib33)). However, these benchmarks tend to focus narrowly on specific domains, leading to potential evaluation biases if a more holistic view of model capabilities is not considered. To address this limitation, several benchmarks have been developed to integrate multiple tasks into a single evaluation framework, including (Wang, [2018](https://arxiv.org/html/2502.19187v2#bib.bib55); Wang et al., [2019](https://arxiv.org/html/2502.19187v2#bib.bib56); Weston et al., [2015](https://arxiv.org/html/2502.19187v2#bib.bib58); Lu et al., [2023](https://arxiv.org/html/2502.19187v2#bib.bib27); Kazemi et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib21); Hendrycks et al., [2020](https://arxiv.org/html/2502.19187v2#bib.bib15); Wang et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib57); Parmar et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib33); Srivastava et al., [2022](https://arxiv.org/html/2502.19187v2#bib.bib45)). Our work builds on this line of research, introducing a new set of challenging tasks for future model evaluation and performance improvement. The multi-task nature of our benchmark with fine-grained tasks each focused on some reasoning skills enables model developers to discover and analyze failure modes in further depth. Note that while private initiatives such as ChatBot Arena ([lmarena,](https://arxiv.org/html/2502.19187v2#bib.bib26)) and the SEAL leaderboard ([ScaleAI,](https://arxiv.org/html/2502.19187v2#bib.bib42)) conduct model evaluations across various aspects, they may suffer from several potential issues as pointed out in Bansal and Maini ([2024](https://arxiv.org/html/2502.19187v2#bib.bib3)). Our benchmark provides an open evaluation framework with an automatic and deterministic scoring mechanism, ensuring full transparency and reproducibility for the broader research community.  
在利用 LLMs 进行数学与科学推理方面，人们给予了极大的重视。这导致了基于数学和 STEM 的评估的流行与激增，例如（Hendrycks 等人，2020；Cobbe 等人，2021），以及最近的（Glazer 等人，2024；Phan 等人，2025）。然而，数学推理技能向更广泛领域的泛化能力仍不明确。事实上，试图使现有基准测试更加稳健的努力——例如 Mirzadeh 等人（2024）——突显了整体上稳健性和逻辑推理能力的缺乏。 为应对特定推理领域，已开发出多项基准测试，涵盖时序推理（Xiong et al., 2024; Beniwal et al., 2024; Dhingra et al., 2022）、空间理解（Bohnet et al., 2024; Yamada et al., 2023; Mirzaee et al., 2021; Shi et al., 2022）、常识推理（Zellers et al., 2019; Talmor et al., 2018; Sakaguchi et al., 2021）以及逻辑推理（Saparov and He, 2022; Tafjord et al., 2020; Saparov et al., 2023; Parmar et al., 2024）。然而，这些基准测试往往局限于特定领域，若未综合考虑模型能力的整体表现，可能导致评估偏差。为弥补这一局限，多项基准测试致力于将多种任务整合至统一评估框架，包括（Wang, 2018; Wang et al., 2019; Weston et al., 2015; Lu et al., 2023; Kazemi et al., 2024; Hendrycks et al., 2020; Wang et al., 2024; Parmar et al., 2024; Srivastava et al., 2022）。本研究在此基础上展开，提出一系列具有挑战性的新任务，旨在推动未来模型评估与性能提升。 我们基准测试的多任务特性，包含针对特定推理技能的细粒度任务，使模型开发者能够更深入地发现和分析失败模式。需要注意的是，尽管像 ChatBot Arena（lmarena）和 SEAL 排行榜（ScaleAI）这样的私人项目在多个方面进行模型评估，但它们可能存在 Bansal 和 Maini（2024）指出的若干潜在问题。我们的基准测试提供了一个开放的评估框架，采用自动且确定性的评分机制，确保为更广泛的研究社区提供完全的透明度和可重复性。

## 3Going Beyond BIG-Bench Hard  
3 超越 BIG-Bench Hard

BIG-Bench, and its later subset BIG-Bench Hard (BBH), have served the research community for several years as _de facto_ benchmarks for measuring general reasoning capabilities. Here, we mainly focus on BBH which has been favored in the recent years. We believe three key factors in the success of BBH were the following: 1- it was challenging even for the frontier models at the time, thus helping reveal model shortcomings and areas for improvement, 2- despite being composed of various tasks, all the questions in BBH were in a way that allowed for simple correctness verification of model responses with a few simple rules, and 3- perhaps most importantly, it tested for a vast array of reasoning skills making it a good proxy for measuring general reasoning. The latter factor is in contrast to many existing reasoning benchmarks that test only for a few of these skills as explained in the related work section.  
BIG-Bench 及其后续子集 BIG-Bench Hard（BBH）多年来一直是衡量通用推理能力的事实基准，为研究界提供了重要支持。近年来，我们主要关注备受青睐的 BBH。我们认为 BBH 的成功主要归功于以下三个关键因素：第一，即便对当时的尖端模型而言，它也具有挑战性，从而有助于揭示模型的不足和改进方向；第二，尽管包含多种任务，但 BBH 中的所有问题都设计得可以通过几条简单规则来验证模型回答的正确性；第三，或许最重要的是，它测试了广泛的推理技能，使其成为衡量通用推理能力的良好指标。最后这一点与许多现有推理基准形成对比，正如相关工作部分所述，那些基准往往只测试其中少数几项技能。

Despite the great success of BBH and its widespread use, it also exhibited some key limitations. Firstly, a random chance baseline already has a high performance on BBH due to the high number of tasks with limited options (8/23 of the tasks have binary labels, and another 5/23 have at most 5 options to choose from). Secondly, some of the problems in BBH can be solved using shortcuts without solving the problem (for example, in the _geometric shapes_ task, whenever there are three _L_ commands the answer is _triangle_). Thirdly, while real-world reasoning problems typically require processing large amounts of input texts, the input lengths of the problems in BBH are often quite short with a macro average of 700 characters across tasks. Fourthly, since the problems were made to be challenging for the LLMs of the time, they typically require only few hops of reasoning. And finally, while BBH tests for a quite large and diverse set of skills, the set can be greatly expanded to include even more reasoning skills. The fast pace of improvement in the reasoning ability of the latest LLMs coupled with the limitations of the BBH dataset outlined above has led to BBH getting saturated with latest models achieving accuracies in the range of 90+ percent on it, thus causing BBH to disappear from the latest model evaluation reports.  
尽管 BBH 取得了巨大成功并被广泛使用，但它也暴露出一些关键局限性。首先，由于大量任务选项有限（23 项任务中有 8 项采用二元标签，另有 5 项最多只有 5 个选项），随机基线在 BBH 上已能获得较高表现。其次，BBH 中的部分问题可通过捷径解决而无需真正理解问题（例如在几何图形任务中，只要出现三个 L 指令答案就是三角形）。第三，现实世界的推理问题通常需要处理大量输入文本，而 BBH 问题的输入长度普遍较短，各任务平均字符数仅为 700。第四，由于这些问题专为挑战当时的 LLMs 而设计，通常仅需少量推理步骤即可解决。最后，虽然 BBH 测试的技能范围相当广泛多样，但仍可大幅扩展以涵盖更多推理技能。 最新 LLMs 推理能力的快速提升，加之上述 BBH 数据集的局限性，导致 BBH 已被最新模型充分掌握——这些模型在其上达到了 90%以上的准确率，从而使 BBH 从最新模型评估报告中消失。

We create a challenging benchmark for measuring the general reasoning capability of LLMs by using BBH as a guide: we preserve the positive aspects of BBH and lift the limitations as much as possible. Specifically, we create a benchmark that is challenging for the frontier models, the correctness of the model responses can be verified automatically despite being composed of several sub-tasks, the random chance baseline has a much lower success rate and the shortcuts are removed from the problems as much as possible, problems require processing longer inputs and require significantly more hops of reasoning to be solved, and, perhaps most importantly, covers a wide array of reasoning skills including those in the original BBH dataset and beyond. Through studying the 23 tasks in BIG-Bench Hard (BBH), we identify that for a reasoner to perform well on BBH it needs to have at least the following broad reasoning skills: 1- temporal understanding, 2- spatial and geometric understanding, 3- commonsense understanding, 4- humour understanding, 5- causal understanding, 6- reasoning about world entities and events, 7- deductive logical reasoning, 8- reasoning through linguistic knowledge, 9- counting and filtering, 10- data structures and algorithms, and 11- performing arithmetic operations.  
我们以 BBH 为蓝本，创建了一个用于衡量 LLMs 通用推理能力的挑战性基准：我们保留了 BBH 的优点，并尽可能消除了其局限性。具体而言，我们构建的基准对前沿模型具有挑战性，模型响应的正确性可以自动验证，尽管它由多个子任务组成；随机猜测基准的成功率要低得多，并且问题中的捷径被尽可能移除；问题需要处理更长的输入，并需要显著更多的推理步骤才能解决；或许最重要的是，它涵盖了广泛的推理技能，包括原始 BBH 数据集中的技能以及其他技能。 通过对 BIG-Bench Hard（BBH）中 23 项任务的研究，我们发现推理模型要在 BBH 上表现出色，至少需要具备以下广泛的推理能力：1-时间理解能力，2-空间与几何理解能力，3-常识理解能力，4-幽默理解能力，5-因果理解能力，6-对世界实体与事件的推理能力，7-演绎逻辑推理能力，8-基于语言知识的推理能力，9-计数与筛选能力，10-数据结构与算法能力，以及 11-执行算术运算的能力。

Figure 2:Sample Questions from 10 tasks. The text has been shortened due to lack of space.  
图 2：来自 10 个任务的示例问题。由于空间不足，文本已被缩短。

For our benchmark, we wish to preserve the high diversity of the reasoning skills and capabilities from BBH and also expand upon it by including more of the following skills. 1- Many-hop reasoning: The ability to solve a problem that require many steps/hops, 2- Very long-range dependency: the ability to remember and use information that have been provided or concluded much earlier in the context, 3- Going against strong prior: the ability to reason through a problem even when it does not match the prior beliefs (McKenzie et al. ([2023](https://arxiv.org/html/2502.19187v2#bib.bib28)) report inverse scaling behaviours in such cases), 4- Learning on the fly: the able to learn something new on the fly (i.e. from the information in the context) and apply it to solve a problem, 5- Dealing with distractors: The ability to identify the parts of information provided that are necessary for solving the problem, and not getting distracted by the redundant information, 6- Long-context: the ability to reason through a long input context and stitching different pieces of input together, 7- Needle in a haystack: the ability to find small pieces of relevant information from a large input (e.g., finding one value from a large table), 8- Finding errors in reasoning traces: the ability to identify the errors in a chain of reasoning not produced by the model itself, 9- Inductive reasoning: the ability to induce patterns from a number of examples and being able to apply the same pattern to a new instance of a problem, 10- Contraint satisfaction: the ability to understand constraints and find a solution that satisfies them, 11- Compositional understanding: the ability to solve multiple independent problems that are fused into one problem (Hosseini et al. ([2024](https://arxiv.org/html/2502.19187v2#bib.bib17)) and Miner et al. ([2024](https://arxiv.org/html/2502.19187v2#bib.bib29)) report higher failure rates than expected in the compositional case), and 12- Knowledge-intense reasoning: the ability to reason in domains where a great amount of domain knowledge is needed.  
在我们的基准测试中，我们希望保留 BBH 中推理技能和能力的多样性，并通过纳入更多以下技能来进一步扩展。 1- 多跳推理：解决需要多个步骤/跳跃的问题的能力，2- 超长程依赖：记忆并利用在上下文早期提供或推导出的信息的能力，3- 对抗强先验：即使问题与先前的信念不符，也能通过推理解决问题的能力（McKenzie 等人（2023）报告了此类情况下的逆缩放行为），4- 即时学习：即时学习新事物（即从上下文信息中）并应用其解决问题的能力，5- 处理干扰信息：识别解决问题所需信息部分，不被冗余信息分散注意力的能力，6- 长上下文：在长输入上下文中进行推理，并将不同输入片段拼接在一起的能力，7- 大海捞针：从大量输入中找出小部分相关信息的能力（例如，从大型表格中找到一个值），8- 发现推理轨迹中的错误：识别非模型自身产生的推理链中错误的能力， 9- 归纳推理：从多个示例中归纳出模式，并能够将相同模式应用于问题的新实例的能力；10- 约束满足：理解约束并找到满足这些约束的解决方案的能力；11- 组合理解：解决多个独立问题融合成一个问题的能力（Hosseini 等人（2024 年）和 Miner 等人（2024 年）报告称，在组合情况下的失败率高于预期）；以及 12- 知识密集型推理：在需要大量领域知识的领域中进行推理的能力。

## 4BIG-Bench Extra Hard  4BIG-Bench 超难版

We create BIG-Bench Extra Hard (BBEH), a dataset that tests the general reasoning capability of models on a wide array of reasoning skills. To this end, we build on the success of BBH and replace each of the 23 tasks in BBH with another task that is in a similar reasoning domain and tests for similar (or more) skills, but is more challenging compared to the original one. Replacing each task with another one in the same domain that tests for similar capabilities ensures that we preserve the high diversity of original BBH dataset. In Table [1](https://arxiv.org/html/2502.19187v2#S4.T1 "Table 1 ‣ 4 BIG-Bench Extra Hard ‣ BIG-Bench Extra Hard"), we outline a high-level description of the new tasks in BBEH, how they have been constructed and which task from BBH the replace, and what reasoning skills they target. The benchmark contains 200 questions per task, except for the _Disambiguation QA_ task where we have 120 questions. For more details about the tasks and some intuitions from the experimental results and model failure modes, see Appendix [A](https://arxiv.org/html/2502.19187v2#A1 "Appendix A Detailed Description of the Tasks and Task-Specific Insights from Experiments ‣ BIG-Bench Extra Hard"). Samples from a few of our tasks are provided in Figure [2](https://arxiv.org/html/2502.19187v2#S3.F2 "Figure 2 ‣ 3 Going Beyond BIG-Bench Hard ‣ BIG-Bench Extra Hard").  
我们创建了 BIG-Bench Extra Hard（BBEH）数据集，旨在广泛测试模型在多种推理技能上的通用推理能力。为此，我们基于 BBH 的成功基础，将其中的 23 个任务逐一替换为另一个任务，这些新任务属于相似的推理领域，测试相似（或更多）的技能，但相比原任务更具挑战性。通过在同一领域内替换任务并保持能力测试的相似性，我们确保了原始 BBH 数据集的高度多样性得以保留。在表 1 中，我们概述了 BBEH 中新任务的高层描述、构建方式、它们替代了 BBH 中的哪些任务，以及它们针对的推理技能。该基准测试中每个任务包含 200 个问题，除了歧义问答任务有 120 个问题。有关任务的更多细节以及实验结果和模型失败模式的一些直观分析，请参见附录 A。图 2 提供了我们部分任务的示例。

|   |   |   |
|---|---|---|
|BBEH task  BBEH 任务|Summary of changes made and the task it replaces from BBH  <br>相对于 BBH 所做的变更总结及所替代的任务|Main reasoning skills  主要推理技能|
|Boardgame QA  棋盘游戏问答|Based on Kazemi et al. ([2023b](https://arxiv.org/html/2502.19187v2#bib.bib20)) but with larger reasoning depth. Requires many hops of deductive logical reasoning, and also requires the model to learn a specific type of conflict resolution on the fly. Replaces Logical Deduction from BBH which needed only a few simple steps of deductive logic.  <br>基于 Kazemi 等人（2023b）的研究，但推理深度更大。需要多步演绎逻辑推理，并要求模型在推理过程中动态学习特定类型的冲突解决机制。取代了 BBH 中仅需少量简单演绎逻辑步骤的"逻辑演绎"任务。|Deductive reasoning, learning on the fly, many-hop reasoning.  <br>演绎推理、动态学习、多步推理。|
|Boolean Expressions  布尔表达式|Requires determining the truth value of an expression whose operands could themselves be textual/mathematical sub-expressions that evaluate to True or False. Replaces the _Boolean Expressions_ task from BBH which can be easily solved through one line of python code.  <br>需要确定一个表达式的真值，其操作数本身可能是可评估为真或假的文本/数学子表达式。取代了 BBH 中可通过一行 Python 代码轻松解决的"布尔表达式"任务。|Logical reasoning, many-hop reasoning.  <br>逻辑推理，多跳推理。|
|Buggy Tables  有缺陷的表格|Requires understanding and reconstructing a large buggy table given the description of the bug, and then computing some conditional queries on it. Replaces _Penguins in a table_ from BBH which required simple operations over small, clean tables.  <br>需要根据错误描述理解和重建一个有缺陷的大型表格，然后对其执行一些条件查询。取代了 BBH 中的"表格中的企鹅"任务，后者仅需对小型、整洁的表格进行简单操作。|Data structures, learning on the fly, needle in haystack  <br>数据结构，即时学习，大海捞针|
|Causal Understanding  因果理解|A subset of the causal stories in Nie et al. ([2023](https://arxiv.org/html/2502.19187v2#bib.bib32)) and improved examples from Kıcıman et al. ([2023](https://arxiv.org/html/2502.19187v2#bib.bib23)). One subtask is focused on testing causal judgment and the other on testing the ability to reason about necessary and sufficient causes. Replaces the _Causal Judgement_ task from BBH.  <br>该任务包含 Nie 等人（2023）研究中因果故事的部分子集，并融合了 Kıcıman 等人（2023）改进的示例。其中一个子任务侧重于测试因果判断能力，另一个则检验对必要原因与充分原因的逻辑推理能力。本任务取代了 BBH 中的"因果判断"任务。|Causal judgement/reasoning, logical reasoning, counterfactual reasoning  <br>因果判断/推理、逻辑推理、反事实推理|
|Disambiguation QA  歧义问答|A task created by the authors, requiring pronoun disambiguation over longer and more challenging text compared to the original _Disambiguation QA_ task in BBH.  <br>由作者创建的任务，相比 BBH 原有的"消歧问答"任务，本任务要求通过更长且更具挑战性的文本来进行代词消歧。|Commonsense understanding, linguistics knowledge.  <br>常识理解，语言学知识。|
|Dyck Language  戴克语言|Involves finding errors in (potentially) faulty solutions to closing a sequence of brackets. It comes from Tyen et al. ([2023](https://arxiv.org/html/2502.19187v2#bib.bib52)) and replaces the _Dyck languages_ task from BBH which requires properly closing brackets as opposed to finding errors.  <br>涉及在（可能）有缺陷的括号闭合序列解决方案中找出错误。该任务源自 Tyen 等人（2023 年）的研究，取代了 BBH 中要求正确闭合括号而非寻找错误的戴克语言任务。|Data structures, finding errors in reasoning traces.  <br>数据结构，在推理轨迹中寻找错误。|
|Geometric Shapes  几何形状|Requires identifying the shapes drawn by a series of SVG commands. Each set of commands can draw multiple shapes and may involve many distracting commands that do not participate in any shape. Replaces the _Geometric Shapes_ from BBH which involved identifying a single shape.  <br>需要识别由一系列 SVG 命令绘制的形状。每组命令可以绘制多个形状，并可能包含许多不参与任何形状绘制的干扰命令。这取代了 BBH 中涉及识别单个形状的几何形状任务。|Spatial reasoning, geometric understanding, dealing with distractors.  <br>空间推理，几何理解，处理干扰项。|
|Hyperbaton  超常语序|Requires inducing correct adjective order given examples on a new variant of English, and properly apply it to new examples. Replaces _Hyperbaton_ from BBH which required simply knowing the correct adjective order in English.  <br>需要根据新变体英语的示例推导出正确的形容词顺序，并将其恰当地应用于新示例。这取代了 BBH 中的 Hyperbaton 任务，后者仅要求了解英语中正确的形容词顺序。|Inductive reasoning, going against strong prior, linguistic knowledge.  <br>归纳推理，违背强烈先验，语言知识。|
|Linguini  语言推理任务|Comes from Sánchez et al. ([2024](https://arxiv.org/html/2502.19187v2#bib.bib38)) and requires linguistic reasoning and inductive reasoning to learn about a new language given some examples and then properly apply those learnings. Replaces _Salient Translation Errors_ from BBH which involved simpler linguistic understanding.  <br>源自 Sánchez 等人（2024 年）的研究，要求通过给定示例进行语言推理和归纳推理来学习一门新语言，并正确应用所学知识。取代了 BBH 中涉及更简单语言理解的显著翻译错误任务。|Inductive reasoning, linguistic knowledge.  <br>归纳推理，语言知识。|
|Movie Recommendation  电影推荐|Given a number of sets of movies, the task is to determine which set has movies that are all likely to be liked by a specific group of people. Replaces _Movie Recommendation_ from BBH which required simple next movie recommendation.  <br>给定若干组电影，任务是确定哪一组电影可能被特定人群全部喜欢。取代了 BBH 中仅需简单推荐下一部电影的电影推荐任务。|Reasoning through knowledge  <br>基于知识的推理|
|Multi-step Arithmetic  多步算术|Requires learning new arithmetic operations and their compositions on the fly, and apply them to evaluate long expressions. Replaces the _Multi-step Arithmetic_ task from BBH which involved simple arithmetic over basic operations.  <br>需要实时学习新的算术运算及其组合，并将其应用于评估长表达式。这取代了 BBH 中的多步算术任务，该任务仅涉及基本运算的简单算术。|Learning on the fly, many-hop reasoning.  <br>实时学习，多跳推理。|
|New Yorker Cartoon Caption (NYCC)  <br>《纽约客》漫画配文（NYCC）|Comes from Hessel et al. ([2022](https://arxiv.org/html/2502.19187v2#bib.bib16)); Zhang et al. ([2024](https://arxiv.org/html/2502.19187v2#bib.bib66)) and requires selecting the funniest caption for an image. We adopt the variant that predicts the best caption only given the textual description of the image. This replaces the _Ruin Names_ task from BBH which involved simpler humour understanding.  <br>源自 Hessel 等人（2022 年）和张等人（2024 年）的研究，要求为图像选择最有趣的配文。我们采用的变体是仅根据图像的文本描述来预测最佳配文。这取代了 BBH 中的"毁坏名字"任务，该任务涉及更简单的幽默理解。|Humour understanding, commonsense understanding.  <br>幽默理解，常识理解。|
|Object Counting  物体计数|Requires counting the number of objects of a certain type given a very long list of various objects and in presence of many types of distractors. Replaces the _Object Counting_ from BBH which required simple counting in a short context.  <br>要求在包含多种干扰项的长列表中，统计特定类型对象的数量。取代了 BBH 中在简短语境下进行简单计数的对象计数任务。|Long-context, (multi-)needle in a haystack, dealing with distractors.  <br>长语境下的"大海捞针"任务，需处理多种干扰项。|
|Object Properties  对象属性|Requires keeping track of a large collection of objects with various properties while they go through multiple rounds of modification. Replaces _Colored Objects_ from BBH which required only recognizing the color of some objects.  <br>要求跟踪大量具有不同属性的对象，并在它们经历多轮修改时保持记录。取代了 BBH 中仅需识别部分对象颜色的彩色对象任务。|Temporal track keeping, long-range dependency.  <br>时间轨迹保持，长程依赖。|
|SARC Triples  SARC 三重任务|Requires understanding sarcasm in Reddit posts and replies. Each problem requires determining the sarcastic-ness of three post/reply pairs. Replaces the _Snark_ task in BBH which required simpler sarcasm understanding.  <br>需要理解 Reddit 帖子和回复中的讽刺。每个问题都需要判断三组帖子/回复对的讽刺程度。取代了 BBH 中需要更简单讽刺理解的 Snark 任务。|Commonsense understanding, sarcasm understanding, simple compositional reasoning.  <br>常识理解，讽刺理解，简单组合推理。|
|Shuffled Objects  乱序对象|A long-context variant of the original _Shuffled Objects_ from BBH which may also require remembering very long-range information.  <br>这是 BBH 中原始乱序对象任务的一个长上下文变体，可能还需要记住非常长距离的信息。|Temporal track keeping, long-context, (multi)-needle in a haystack, long-range dependency.  <br>时间轨迹追踪、长上下文、（多）大海捞针、长距离依赖。|
|Spatial Reasoning  空间推理|Adopts the SpatialLLMEval (Yamada et al., [2023](https://arxiv.org/html/2502.19187v2#bib.bib62)) dataset which requires spatial reasoning over various complex patterns. We expanded the dataset with problems that require many-hops of reasoning and require both forward reasoning from the premises to the goal and backward thinking from the goal to the premises. Replaces the _navigation_ task from BBH which requires much simpler spatial understanding of navigation signals.  <br>采用 SpatialLLMEval（Yamada 等人，2023）数据集，该数据集要求对各种复杂模式进行空间推理。我们扩展了该数据集，增加了需要多步推理的问题，这些问题既需要从前提到目标的正向推理，也需要从目标到前提的反向思考。替换了 BBH 中的导航任务，该任务仅需对导航信号进行更简单的空间理解。|Spatial understanding, many-hop reasoning, long-range dependency.  <br>空间理解、多步推理、长程依赖。|
|SportQA|Comes from Xia et al. ([2024](https://arxiv.org/html/2502.19187v2#bib.bib60)) and requires reasoning combined with a high amount of sports knowledge. We use the hardest subset that contains compositional questions, where each problem contains one main question and multiple sub-questions. Replaces _Sport Understanding_ from BBH which needed much simpler reasoning over sport knowledge.  <br>源自 Xia 等人（2024）的研究，需要结合大量体育知识进行推理。我们使用包含组合性问题的最难子集，其中每个问题包含一个主要问题和多个子问题。替换了 BBH 中的体育理解任务，该任务仅需对体育知识进行更简单的推理。|Knowledge-intensive reasoning, compositional reasoning.  <br>知识密集型推理，组合式推理。|
|Temporal Sequences  时间序列|Requires finding proper meeting times given multiple calendars (each corresponding to a temporal sequence) and various constraints. Replaces the _Temporal Sequence_ task from BBH which involves understanding only a single sequence.  <br>需要根据多个日历（每个对应一个时间序列）和各种约束条件找到合适的会议时间。取代了 BBH 中的时间序列任务，该任务仅涉及理解单个序列。|Temporal understanding, constraints satisfaction.  <br>时间理解，约束满足。|
|Time Arithmetic  时间运算|Comes from the Test of Time benchmark (Fatemi et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib9)) and involves various operations over various representations of date/time. We created a compositional version of this task following (Hosseini et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib17)). Replaces the _Date Understanding_ task from BBH which involved significantly simpler operations over dates.  <br>源自时间测试基准（Fatemi 等人，2024 年），涉及对各种日期/时间表示形式进行多种操作。我们按照 Hosseini 等人（2024 年）的方法创建了该任务的组合版本。取代了 BBH 中的日期理解任务，该任务仅涉及对日期进行简单得多的操作。|Temporal reasoning, compositional understanding.  <br>时间推理，组合理解。|
|Web of Lies  谎言网络|Requires many-hop reasoning to predict the truthfulness of a set of people, and contains two subsets: one coming from the variant used in LiveBench (White et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib59)) and one novel variant that involves cases where the truthfulness of some individuals remains unknown but new conclusions can be drawn from it nevertheless. Replaces the _Web of Lies_ from BBH which involved simpler cases of this problem.  <br>需要多步推理来预测一组人的真实性，包含两个子集：一个来自 LiveBench（White 等人，2024）中使用的变体，另一个是新颖变体，涉及某些个体的真实性未知但仍可从中得出新结论的情况。取代了 BBH 中涉及该问题较简单案例的谎言网络。|Logical reasoning, many-hop reasoning.  <br>逻辑推理，多跳推理。|
|Word Sorting  单词排序|Contains two subtasks: 1- sorting over a modified alphabet order, which goes against the strong prior of the model, and 2- finding errors in sorting traces. Replaces the original Word Sorting task which required simple sorting.  <br>包含两个子任务：1- 基于修改后的字母顺序进行排序，这违背了模型的强烈先验；2- 在排序轨迹中找出错误。取代了原版仅需简单排序的单词排序任务。|Apply algorithms, Going against strong prior, Finding errors in reasoning traces.  <br>应用算法、违背强烈先验、在推理轨迹中寻找错误。|
|Zebra Puzzles  斑马谜题|Puzzles that require various logical deductions to be solved. We add distracting clues to the puzzles to make them more challenging. The dataset is an expanded version of the one from Shah et al. ([2024](https://arxiv.org/html/2502.19187v2#bib.bib43)) and replaces _Formal Fallacies_ from BBH which requires understanding logic and formal fallacies in much simpler setups.  <br>需要运用多种逻辑推理才能解决的谜题。我们在谜题中添加了干扰线索以增加挑战性。该数据集是 Shah 等人（2024）版本的扩展，并取代了 BBH 中的形式谬误任务——后者要求在更简单的设置中理解逻辑和形式谬误。|Constraint satisfaction, many-hop reasoning, dealing with distractors, long-range dependency.  <br>约束满足、多跳推理、处理干扰项、长程依赖。|

Table 1:The tasks in BBEH in alphabetical order of the names, a high-level description of what they test for, the reasoning capabilities that they probe, and the task from BBH that they replace.  
表 1：BBEH 中的任务按名称字母顺序排列，包含对测试内容的高层描述、所探究的推理能力，以及它们替代的 BBH 任务。

A key challenge in creating benchmarks is ensuring they remain difficult for frontier models. This is particularly true for reasoning benchmarks, given the rapid progress in the field over the past year, and especially for BBEH, which comprises 23 distinct tasks, each requiring careful design. To ensure our tasks challenge frontier models, we adopted a semi-adversarial approach. We selected two strong reference models: one general-purpose and one specialized in reasoning. We iteratively increased task difficulty while keeping in mind the extra skills that we wanted our benchmark to test for, evaluating the reference models on each new iteration. If a task proved insufficiently challenging, we either replaced it with another task or added extra types of difficulty and re-evaluated until the difficulty level was satisfactory. We used Gemini 1.5 Flash (Team et al., [2024a](https://arxiv.org/html/2502.19187v2#bib.bib49)) as our general-purpose reference model and the Gemini Thinking Experimental model as our reasoning-specialized reference model (initially the December 2024 version but later changed to the January 2025 version, known as Gemini-2.0-Flash-Thinking-Exp-01-21). These models were chosen for their performance and the speed of generating outputs, which facilitated rapid iteration during task construction. We iterated on each task until both reference models achieved an accuracy below 70%.  
创建基准测试的一个关键挑战在于确保它们对前沿模型保持难度。这一点对于推理基准测试尤为突出，考虑到过去一年该领域的快速进展，特别是对于 BBEH 而言，它包含 23 个独立任务，每个任务都需要精心设计。为确保我们的任务能够挑战前沿模型，我们采用了半对抗性方法。我们选择了两个强大的参考模型：一个通用模型和一个专门用于推理的模型。在迭代增加任务难度的同时，我们牢记我们希望基准测试额外检验的技能，并在每次新迭代中对参考模型进行评估。如果某个任务被证明挑战性不足，我们会用另一个任务替换它，或者增加额外的难度类型并重新评估，直到难度水平令人满意。我们使用 Gemini 1.5 Flash（Team 等人，2024a）作为通用参考模型，并使用 Gemini Thinking Experimental 模型作为推理专用参考模型（最初是 2024 年 12 月版本，后来改为 2025 年 1 月版本，即 Gemini-2.0-Flash-Thinking-Exp-01-21）。 选择这些模型是基于其性能表现和生成输出的速度，这有助于在任务构建过程中快速迭代。我们对每个任务进行了迭代，直到两个参考模型的准确率都低于 70%。

In most cases, we tried to use the reference models only as a black box that provided feedback on the difficulty of our tasks. In some cases, however, making tasks more difficult required looking into the approach adopted by the model. As an example, the original "Boolean Expression" task in BBH required models to evaluate the truth value of expressions such as _(not True) or False_. Our initial attempt to increase difficulty involved creating longer expressions with significantly more clauses. However, our reference model achieved high accuracy regardless of the number of clauses. While initially this seemed surprising, upon investigating the model’s approach, we discovered it cleverly used Python to solve the problem by directly evaluating the expression: _result = <expression>; print(result)_. Thus, adding more clauses did not have much effect in increasing difficulty. Our next step was to prevent the model from using Python. We achieved this by replacing some "True" and "False" clauses with sentences that evaluated to the same truth value (e.g., replacing "True" with "The capital of Canada is Ottawa.").  
在大多数情况下，我们尝试仅将参考模型视为黑盒，用于评估任务难度。然而，在某些情况下，提升任务难度需要深入探究模型采用的方法。例如，BBH 中的原始"布尔表达式"任务要求模型评估诸如(not True) or False 等表达式的真值。我们最初尝试通过创建包含更多子句的更长表达式来增加难度。但无论子句数量多少，参考模型都保持了高准确率。起初这令人惊讶，但在研究模型方法后，我们发现它巧妙地利用 Python 直接评估表达式来解决问题：result = <表达式>; print(result)。因此，增加子句数量对提升难度影响甚微。我们的下一步是阻止模型使用 Python。我们通过将部分"True"和"False"子句替换为具有相同真值的句子来实现这一点（例如，将"True"替换为"加拿大的首都是渥太华。"）。

Given the similarity of the high-level approach in creating LLM reasoners (architecture, training phases, etc.), we believe our semi-adversarial benchmark construction can lead to a benchmark that is also challenging for non-reference models. This is confirmed by the experimental results in the following sections. However, this approach also has some notable limitations. Firstly, the choice of the reference model will unavoidably bias the benchmark towards certain types of failure modes. For instance, had our reference model not used code to solve the multi-hop Boolean expressions, we might have stopped there, resulting in a task too easy for models that appropriately trigger code. We tried to mitigate this as much as possible by using strong reference models, and by avoiding over-engineering to the reference model failures. Secondly, since the benchmark is created adversarially with respect to the reference models, a fair comparison of the reference and non-reference models may not be possible. We expect this limitation to be temporary and be resolved when newer versions of the reference models become available.  
鉴于创建 LLM 推理器的高层方法（架构、训练阶段等）具有相似性，我们相信半对抗式基准构建方法能够产生对非参考模型同样具有挑战性的基准。后续章节的实验结果证实了这一点。然而，这种方法也存在一些显著局限性。首先，参考模型的选择不可避免地会使基准偏向特定类型的失效模式。例如，若我们的参考模型未使用代码解决多跳布尔表达式问题，我们可能就此止步，导致该任务对能恰当调用代码的模型而言过于简单。我们尝试通过采用强参考模型、避免针对参考模型失效进行过度设计来尽可能缓解这一问题。其次，由于基准是相对于参考模型以对抗方式构建的，对参考模型与非参考模型进行公平比较可能无法实现。我们预计这一局限性是暂时的，当新版参考模型可用时将得到解决。

BBEH Mini: Besides reporting results on BBEH, we also report results on a smaller subset called _BBEH Mini_ which contains 460 examples overall (20 examples randomly selected from each task). This subset can be used for faster and cheaper experimentations.  
BBEH Mini：除了报告 BBEH 的结果外，我们还报告了一个名为 BBEH Mini 的较小子集的结果，该子集总共包含 460 个示例（每个任务中随机选择 20 个示例）。这个子集可用于更快、更便宜的实验。

![Refer to caption](https://arxiv.org/html/2502.19187v2/x2.png)

Figure 3: A comparison of the average input lengths of the tasks in BBEH to their counterparts in BBH.  
图 3：BBEH 任务与其在 BBH 中的对应任务平均输入长度对比。

## 5Results and Analyses  5 结果与分析

We start by analyzing BBEH and comparing it against its counterpart, BBH. We then report results on BBEH for various models and compare their performances. Then, we provide some extra analysis of the results revealing interesting insights about where reasoning-specialized and larger models gain more and where they gain less compared to general-purpose and smaller models respectively. We also provide a large body of observations and insights from task-specific results in Appendix [A](https://arxiv.org/html/2502.19187v2#A1 "Appendix A Detailed Description of the Tasks and Task-Specific Insights from Experiments ‣ BIG-Bench Extra Hard").  
我们首先分析 BBEH 并与对应的 BBH 进行比较。随后，我们报告了不同模型在 BBEH 上的结果，并对比它们的性能表现。接着，我们对结果进行了额外分析，揭示了推理专用模型与通用模型、大型模型与小型模型相比，在哪些方面表现更优或稍逊的有趣见解。此外，我们在附录 A 中提供了大量基于具体任务结果的观察与洞见。

### 5.1BBEH Analysis  5.1BBEH 分析

Input/Context Length: As mentioned in Section [3](https://arxiv.org/html/2502.19187v2#S3 "3 Going Beyond BIG-Bench Hard ‣ BIG-Bench Extra Hard"), the problems in the original BBH dataset are mostly short. On the contrary, the problems in BBEH tend to be quite long and require a great amount of input processing by the models. Figure [3](https://arxiv.org/html/2502.19187v2#S4.F3 "Figure 3 ‣ 4 BIG-Bench Extra Hard ‣ BIG-Bench Extra Hard") compares the average input lengths of each of the tasks in BBEH with their counterpart from BBH. From the figure, one can observe how input lengths have increased for almost all the tasks (except two), sometimes quite significantly. The macro average context length of the tasks in BBEH is about six times bigger than that of BBH.  
输入/上下文长度：如第 3 节所述，原始 BBH 数据集中的问题大多较短。相反，BBEH 中的问题往往相当长，需要模型进行大量的输入处理。图 3 比较了 BBEH 中各项任务与其在 BBH 中对应任务的平均输入长度。从图中可以看出，几乎所有任务（除两项外）的输入长度都有所增加，有时增幅相当显著。BBEH 中任务的宏观平均上下文长度大约是 BBH 的六倍。

Required Amount of Thinking: Many of the problems in BBH only require few hops of reasoning, sometimes not requiring a great amount of thinking. As a proxy for measuring the amount of thinking required by BBEH and compare it to BBH, we compare the average length of the outputs generated by a fixed model (Gemini 2.0 Flash) for the two datasets. The results are presented in Figure [4](https://arxiv.org/html/2502.19187v2#S5.F4 "Figure 4 ‣ 5.1 BBEH Analysis ‣ 5 Results and Analyses ‣ BIG-Bench Extra Hard"). From the figure, we can observe that the average length of the output has significantly increased for every single one of the tasks in BBEH compared to their counterpart in BBH, thus providing evidence that the problems in BBEH may require much more thinking. The macro average output length of the responses for tasks in BBEH is about seven times bigger than that of BBH.  
所需思考量：BBH 中的许多问题仅需少量推理步骤，有时并不需要大量思考。作为衡量 BBEH 所需思考量并与 BBH 对比的代理指标，我们比较了固定模型（Gemini 2.0 Flash）对两个数据集生成答案的平均长度。结果如图 4 所示。从图中可以观察到，与 BBH 中的对应任务相比，BBEH 中每个任务的输出平均长度均显著增加，这证明 BBEH 中的问题可能需要更多的思考。BBEH 任务回答的宏观平均输出长度约为 BBH 的七倍。

![Refer to caption](https://arxiv.org/html/2502.19187v2/x3.png)

Figure 4: A comparison of the average output lengths of the Gemini 2.0 Flash responses for each of the tasks in BBEH and their counterparts in BBH.  
图 4：BBEH 任务与 BBH 任务中 Gemini 2.0 Flash 响应平均输出长度的对比。

|   |   |   |   |   |   |   |   |   |   |   |   |   |   |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|Tasks/Models|Random  随机|Qwen-2.5-7B-Instruct|Llama 3.1 8b Instruct  Llama 3.1 8b 指令版|Gemma2 27b IT|Gemma3 4b|Gemma3 12b|Gemma3 27b|Gemini 2.0 Flash-Lite  双子座 2.0 闪亮轻量版|Gemini 2.0 Flash  Gemini 2.0 闪电版|GPT4o|Distill R1 Qwen 32b  蒸馏 R1 Qwen 32b|DeepSeek R1|o3-mini (high)  o3-mini（高）|
|BoardgameQA  棋盘游戏问答|33.3|31.0|31.5|39.5|34.5|33.0|37.0|29.5|42.5|41.0|36.0|75.5|53.0|
|Boolean Expressions  布尔表达式|20.0|22.0|18.0|25.0|23.0|25.5|22.0|24.0|27.0|22.5|17.5|55.5|67.0|
|Buggy Tables  错误表格|0.0|1.5|0.0|0.5|0.5|0.0|0.0|1.5|3.5|0.5|0.5|4.5|59.5|
|Causal Understanding  因果理解|38.0|40.0|37.0|45.5|46.0|49.0|51.5|52.5|52.0|54.0|54.5|54.5|54.0|
|DisambiguationQA  歧义问答|21.0|34.2|36.7|45.0|33.3|41.7|49.2|50.0|48.3|51.7|52.5|50.0|58.3|
|Dyck Languages  戴克语言|1.4|1.0|4.5|2.0|3.5|8.5|4.5|6.5|14.0|8.0|18.0|56.0|55.0|
|Geometric Shapes  几何形状|6.2|41.5|25.5|31.0|18.0|32.5|26.5|30.0|35.0|22.5|4.5|1.5|52.5|
|Hyperbaton  超常语序|0.0|0.5|2.0|4.0|2.0|2.5|3.5|6.5|4.5|7.5|3.0|6.0|32.0|
|Linguini|0.0|2.5|3.0|7.0|1.0|6.0|9.0|12.5|15.5|15.5|6.0|19.5|17.0|
|Movie Recommendation  电影推荐|10.0|24.5|30.0|40.0|35.0|44.5|55.0|51.5|59.5|61.0|46.0|59.5|84.0|
|Multistep Arithmetic  多步骤算术|0.0|0.0|0.5|0.0|0.0|0.5|1.5|7.5|9.5|5.5|36.0|46.5|73.0|
|NYCC|10.0|13.0|13.0|13.5|7.0|11.5|15.0|13.5|11.0|23.0|10.5|20.0|16.0|
|Object Counting  物体计数|0.0|0.0|0.0|0.0|0.0|0.5|0.0|4.0|11.0|6.5|4.0|76.5|90.0|
|Object Properties  物体属性|1.6|0.0|0.5|0.0|0.5|1.5|0.5|0.5|1.5|0.0|0.0|0.0|56.5|
|SARC Triples  SARC 三元组|12.5|17.5|16.5|21.0|14.0|26.0|24.0|27.0|37.5|38.5|22.0|28.5|24.0|
|Shuffled Objects  打乱的对象|14.3|8.0|9.5|12.0|1.0|7.0|5.0|15.0|9.0|14.0|2.0|6.0|49.5|
|Spatial Reasoning  空间推理|5.2|0.0|1.0|7.0|4.0|10.5|13.0|10.5|18.5|14.0|14.5|37.0|48.5|
|SportQA  体育问答|0.0|5.0|1.5|10.0|2.5|12.5|20.0|18.5|23.0|25.0|19.5|29.0|26.5|
|Temporal Sequences  时间序列|0.0|0.5|9.5|1.5|1.0|0.0|1.5|1.0|0.5|0.0|0.5|0.0|68.5|
|Time Arithmetic  时间运算|0.5|18.5|4.0|15.5|9.5|23.5|46.5|45.0|48.0|45.5|56.5|77.0|76.5|
|Web of Lies  谎言网络|5.5|2.5|5.5|6.5|12.0|22.0|21.0|14.0|18.5|14.5|13.0|29.5|43.0|
|Word Sorting  单词排序|4.3|4.0|2.5|3.5|4.5|6.0|7.5|12.5|26.0|22.0|36.0|68.0|77.5|
|Zebra Puzzles  斑马谜题|15.4|19.0|2.5|23.0|10.0|19.5|30.0|32.0|44.5|32.0|1.5|8.0|67.5|
|BBEH|2.4|3.0|3.6|4.0|3.4|4.5|4.9|8.0|9.8|6.0|5.2|6.8|44.8|

Table 2:The performance of various models on the individual tasks and overall on BBEH.  
表 2：各模型在 BBEH 各项任务及整体上的表现。

### 5.2Model Evaluations  5.2 模型评估

Models: We evaluate various models on BBEH and compare their performance across individual tasks and on the entire dataset. Specifically, we experiment with models from the following families: Llama 3.1 (Dubey et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib8)), Qwen 2.5 Yang et al. ([2024a](https://arxiv.org/html/2502.19187v2#bib.bib63)), Gemma2 (Team et al., [2024b](https://arxiv.org/html/2502.19187v2#bib.bib50)), Gemma3 (Team et al., [2025](https://arxiv.org/html/2502.19187v2#bib.bib51)), Gemini 2.0, GPT4o (the latest version, 2024-11-20, at the time of the experiments) (Achiam et al., [2023](https://arxiv.org/html/2502.19187v2#bib.bib1)), DeepSeek R1 and the Distilled model in Qwen 32b (Guo et al., [2025](https://arxiv.org/html/2502.19187v2#bib.bib11)), and o3-mini (high)11[https://openai.com/index/openai-o3-mini/](https://openai.com/index/openai-o3-mini/)  
模型：我们在 BBEH 上评估了多种模型，并比较了它们在各个任务以及整个数据集上的表现。具体来说，我们实验了以下系列的模型：Llama 3.1 (Dubey et al., 2024)、Qwen 2.5 Yang et al. (2024a)、Gemma2 (Team et al., 2024b)、Gemma3 (Team et al., 2025)、Gemini 2.0、GPT4o（实验时的最新版本，2024-11-20）(Achiam et al., 2023)、DeepSeek R1 和 Qwen 32b 中的蒸馏模型 (Guo et al., 2025)，以及 o3-mini (high) 1 。.

Metric: Given the highly versatile use-cases of the current LLM reasoners, they should be capable across the board to excel at real-world problems and be robust general reasoners. However, we find that micro and macro averages (which are often used for benchmarks composed of multiple tasks), fail to capture this crucial aspect. These metrics are susceptible to distortion by outlier performance, potentially presenting a misleadingly optimistic assessment when a model excels in a limited subset of tasks while faltering in others. To address this, we employ the (adjusted) harmonic mean22To deal with zero values, we add a value of 1 to all accuracy numbers.  
为处理零值情况，我们在所有准确率数值上添加 1 值。  
指标：鉴于当前 LLM 推理器的高度多样化应用场景，它们应当具备全面应对现实世界问题并成为稳健通用推理器的能力。然而我们发现，微观和宏观平均值（常用于由多个任务组成的基准测试）未能捕捉这一关键维度。这些指标易受异常性能的扭曲，当模型在有限任务子集表现出色而在其他任务中表现不佳时，可能导致具有误导性的乐观评估。为解决此问题，我们采用（调整后的）调和平均数 2 as our primary evaluation metric for BBEH. The harmonic mean provides a more conservative and balanced representation of overall performance, effectively penalizing models with significant performance disparities across different tasks, thereby aligning more closely with the requirement for consistent, general reasoning capabilities. For BBEH Mini, due to the small number of examples per task, we adopt micro average.  
作为 BBEH 的主要评估指标。调和平均数能更保守、均衡地反映整体性能，有效惩罚在不同任务间表现差异显著的模型，从而更贴合对一致、通用推理能力的要求。对于 BBEH Mini，由于每个任务的样本量较小，我们采用微平均法。

The results for each task and on the entire dataset for each model is presented in Table [2](https://arxiv.org/html/2502.19187v2#S5.T2 "Table 2 ‣ 5.1 BBEH Analysis ‣ 5 Results and Analyses ‣ BIG-Bench Extra Hard") for BBEH and in Table [3](https://arxiv.org/html/2502.19187v2#S5.T3 "Table 3 ‣ 5.2 Model Evaluations ‣ 5 Results and Analyses ‣ BIG-Bench Extra Hard") for BBEH Mini. According to the results, we make several interesting observations. Firstly, we observe a large headroom not only for the individual tasks, but also for BBEH overall. The best performance for the general-purpose models is at 9.8% harmonic mean accuracy. The reasoning-specialized models are expectedly performing better than the general-purpose models on the benchmark, but the best performance for these models is still at 44.8% on BBEH. Despite the adversarial construction, the reference Thinking model achieves a harmonic mean accuracy of 20.2% on BBEH. Note that while we calibrated the difficulty with respect to two reference models so their accuracies fall below 70%, the difficulty mostly carries to other models too with o3-mini (high) exceeding 70% accuracy only on 4 out of 23 tasks, DeepSeek R1 exceeding it only on 3 out of 23 tasks, and other models never exceeding it. Note that some model accuracies are even below random performance. Upon checking, we observe that these are mostly cases where models could not solve the problem in their effective output token lengths and started degenerating after a point, so no final answer could be extracted from their solution.  
各模型在每项任务及整个数据集上的结果分别展示于表 2（针对 BBEH）和表 3（针对 BBEH Mini）。根据结果，我们得出若干值得关注的发现。首先，我们观察到不仅在单个任务中存在巨大提升空间，BBEH 整体亦然。通用模型的最佳表现仅为 9.8%的调和平均准确率。虽然推理专用模型在基准测试中表现优于通用模型符合预期，但这类模型在 BBEH 上的最佳准确率仍停留在 44.8%。尽管采用了对抗性构建，参考思维模型在 BBEH 上仍实现了 20.2%的调和平均准确率。需要说明的是，虽然我们根据两个参考模型校准了难度设定，使其准确率低于 70%，但这种难度设定对其他模型同样具有挑战性——o3-mini（高配版）仅在 23 项任务中的 4 项超过 70%准确率，DeepSeek R1 仅在 3 项任务中超过该阈值，而其他模型均未突破此界限。值得注意的是，部分模型的准确率甚至低于随机猜测水平。 经核查，我们发现这些情况大多是因为模型无法在其有效输出标记长度内解决问题，并在某个节点后开始退化，因此无法从其解决方案中提取出最终答案。

Secondly, for completeness, we also report micro average accuracies in Table [4](https://arxiv.org/html/2502.19187v2#A0.T4 "Table 4 ‣ BIG-Bench Extra Hard") (in Appendix) according to which we observe that the best general-purpose model has a micro average accuracy of 23.9% and the best reasoning-specialized model has an accuracy of 54.2%. Interestingly, while DeepSeek R1 performs better than all general-purpose models in terms of micro average accuracy, given its low performance on some of our tasks it performs worse than two of the general-purpose models in terms of harmonic mean accuracy.  
其次，为了全面性，我们还在附录的表 4 中报告了微平均准确率。根据该表，我们观察到最佳通用模型的微平均准确率为 23.9%，而最佳推理专用模型的准确率为 54.2%。有趣的是，尽管 DeepSeek R1 在微平均准确率方面优于所有通用模型，但由于其在某些任务上的表现较低，其在调和平均准确率方面却逊于两款通用模型。

Thirdly, as mentioned in Section [3](https://arxiv.org/html/2502.19187v2#S3 "3 Going Beyond BIG-Bench Hard ‣ BIG-Bench Extra Hard"), the problems in the original BBH dataset suffered from having a small output space, thus allowing for a random baseline to have a high performance. In Table [2](https://arxiv.org/html/2502.19187v2#S5.T2 "Table 2 ‣ 5.1 BBEH Analysis ‣ 5 Results and Analyses ‣ BIG-Bench Extra Hard"), we provide the results of a random baseline for each of the tasks in BBEH and the entire dataset. As can be viewed, the random baseline has a performance of 8.4% for BBEH which leaves substantial room for comparing models of various size.  
第三，如第 3 节所述，原始 BBH 数据集中的问题存在输出空间较小的问题，导致随机基线能够获得较高的性能。在表 2 中，我们提供了 BBEH 中每个任务以及整个数据集的随机基线结果。可以看出，随机基线在 BBEH 上的性能为 8.4% ，这为比较不同规模的模型留下了充足的空间。

Finally, looking at the accuracies of the models on various tasks, we can see that various models are good at different types of reasoning. For example, DeepSeek R1 significantly outperforms other models on BoardgameQA, o3-mini (high) significantly outperforms other models on Temporal Sequences and Object Properties, GPT4o significantly outperforms other models on NYCC, and GPT4o and Gemini 2.0 Flash significantly outperform other models on SARC Triples.  
最后，观察各模型在不同任务上的准确率，可以发现不同模型擅长不同类型的推理。例如，DeepSeek R1 在 BoardgameQA 上显著优于其他模型，o3-mini（高配版）在时间序列和对象属性任务上明显领先，GPT4o 在 NYCC 测试中表现突出，而 GPT4o 与 Gemini 2.0 Flash 在 SARC 三元组任务上均展现出显著优势。

|   |   |   |   |   |   |   |   |   |   |   |   |
|---|---|---|---|---|---|---|---|---|---|---|---|
|Tasks/Models  任务/模型|Llama 3.1 8b Instruct  Llama 3.1 8b 指令版|Gemma2 27b IT|Gemma3 4b|Gemma3 12b  杰玛 3 12b 版|Gemma3 27b  杰玛 3 27b 版|Gemini 2.0 Flash-Lite  双子座 2.0 闪亮轻量版|Gemini 2.0 Flash  双子座 2.0 闪存版|GPT4o|Distill R1 Qwen 32b  蒸馏 R1 Qwen 32b|DeepSeek R1|o3-mini (high)|
|BBEH Mini  BBEH 迷你版(Micro Average)  （微平均）|11.5|15.0|13.3|14.3|17.4|22.2|27.0|23.5|15.4|37.2|56.7|

Table 3:The performance of various models on BBEH Mini (micro average).  
表 3：各模型在 BBEH Mini（微平均）上的表现。

### 5.3Further Analyses of the Results  
5.3 结果的进一步分析

General-Purpose vs Reasoning Models: With the introduction of reasoning models that leverage test-time compute for thinking, a tremendous jump in performance was observed on reasoning tasks involving math and coding. For example, on the AIME2024 dataset, the performance of GPT4o was 13.4%, but the o1 model increased it to 83.3% and o3-mini (high) increased it further to 87.3%. Here, we examine whether the same is true for various types of general reasoning. In Figure [5](https://arxiv.org/html/2502.19187v2#S5.F5 "Figure 5 ‣ 5.3 Further Analyses of the Results ‣ 5 Results and Analyses ‣ BIG-Bench Extra Hard"), we compare o3-mini (high) and GPT4o, as examples of reasoning and general models respectively, on each of the tasks from BBEH and sort the tasks ascending based on how much o3-mini (high) gains over GPT4o. We observe that the tasks that gain the most are those involving counting, planning, arithmetic, and data structures and algorithms. Whereas the tasks that gain the least (or sometimes negatively) are mostly those involving commensense, humour, sarcasm, and causation. Our results indicate that reasoning models achieve the most significant gains when applied to formal problems and demonstrate limited progress in handling the softer reasoning skills which are typically needed for complex, real-world scenarios.  
通用模型与推理模型对比：随着利用测试时计算进行思考的推理模型问世，在涉及数学和编程的推理任务上观察到了性能的巨大飞跃。例如，在 AIME2024 数据集上，GPT4o 的表现仅为 13.4%，而 o1 模型将其提升至 83.3%，o3-mini（高）模型进一步将其提升至 87.3%。在此，我们探讨不同类型的通用推理是否也存在同样的现象。在图 5 中，我们分别以 o3-mini（高）和 GPT4o 作为推理模型和通用模型的代表，对 BBEH 中的各项任务进行比较，并按照 o3-mini（高）相对于 GPT4o 的提升幅度对任务进行升序排序。我们观察到，提升幅度最大的任务主要涉及计数、规划、算术以及数据结构和算法。而提升幅度最小（有时甚至为负）的任务则大多涉及常识、幽默、讽刺和因果关系。我们的结果表明，推理模型在解决形式化问题时取得了最显著的进步，但在处理复杂现实场景中通常所需的软性推理技能方面进展有限。

The Effect of Model Size: We also explore the effect of model size on the performance of the models across various types of general reasoning. In Figure [6](https://arxiv.org/html/2502.19187v2#S5.F6 "Figure 6 ‣ 5.3 Further Analyses of the Results ‣ 5 Results and Analyses ‣ BIG-Bench Extra Hard"), we compare Gemini 2.0 Flash against Gemini 2.0 Flash-Lite on different tasks from BBEH and sort the tasks ascending based on how much Flash gains over Flash-Lite33Since in some cases these models perform below random chance due to not generating an extractable final answer, to reduce noise we take the maximum of their performance and the random chance performance for each task.  
由于在某些情况下，这些模型因未能生成可提取的最终答案而表现低于随机概率，为减少噪声，我们取每个任务中模型表现与随机概率表现的最大值。  
模型规模的影响：我们还探讨了模型规模对各类通用推理任务表现的影响。在图 6 中，我们将 Gemini 2.0 Flash 与 Gemini 2.0 Flash-Lite 在 BBEH 的不同任务上进行比较，并根据 Flash 相对于 Flash-Lite 的提升幅度对任务进行升序排序。. While the signal is not as clear as the case where we compared general models against reasoning models, we still observe that the tasks related to humour, commonsense, and causal reasoning are the ones with the least gains, and tasks requiring many-hop reasoning or applying algorithms are the ones with the largest gains. A particular exception is the SARC Triples task which is a sarcasm understanding and where the gains are large. This could in part be due to the fact that each example in SARC Triples is a composition of three sub-questions, and larger models may be better at dealing with such composite questions.  
虽然信号不如我们比较通用模型与推理模型时那样清晰，但我们仍观察到与幽默、常识和因果推理相关的任务提升幅度最小，而需要多跳推理或应用算法的任务提升幅度最大。一个特例是 SARC Triples 任务，这是一个讽刺理解任务，其提升幅度较大。这可能部分是因为 SARC Triples 中的每个示例都由三个子问题组成，而更大的模型可能更擅长处理此类复合问题。

![Refer to caption](https://arxiv.org/html/2502.19187v2/x4.png)

Figure 5: Performance gains (absolute) of o3-mini (high) over GPT-4o on BBEH tasks. Tasks are ordered by the magnitude of improvement, with green signifying substantial gains and yellow/red signifying minimal or negative gains.  
图 5：o3-mini（高）在 BBEH 任务上相对于 GPT-4o 的性能提升（绝对值）。任务按改进幅度排序，绿色表示显著提升，黄色/红色表示提升极小或负提升。

![Refer to caption](https://arxiv.org/html/2502.19187v2/x5.png)

Figure 6: Performance gains (absolute) of Gemini 2.0 Flash over Gemini 2.0 Flash-Lite on BBEH tasks. Tasks are ordered by the magnitude of improvement, with green signifying substantial gains and yellow/red signifying minimal or negative gains.  
图 6：Gemini 2.0 Flash 在 BBEH 任务上相较于 Gemini 2.0 Flash-Lite 的性能提升（绝对值）。任务按提升幅度排序，绿色表示显著提升，黄色/红色表示提升微小或负提升。

![Refer to caption](https://arxiv.org/html/2502.19187v2/x6.png)

![Refer to caption](https://arxiv.org/html/2502.19187v2/x7.png)

Figure 7:Performance gains as a function of (left) context length and (right) output length (proxy for required thinking). A scatter plot and trendlines for the gains obtained by a reasoning-specialized model (o3-mini high) vs a general-purpose model (GPT4o) and a larger model (Gemini 2.0 Flash) vs a smaller model (Gemini 2.0 Flash-Lite), as a function of (left) the average context lengths and (right) the average output lengths (same values as in Figure [4](https://arxiv.org/html/2502.19187v2#S5.F4 "Figure 4 ‣ 5.1 BBEH Analysis ‣ 5 Results and Analyses ‣ BIG-Bench Extra Hard")), for the tasks in BBEH.  
图 7：性能提升与（左）上下文长度和（右）输出长度（作为所需思考的代理变量）的函数关系。针对 BBEH 中的任务，展示了推理专用模型（o3-mini high）与通用模型（GPT4o）以及较大模型（Gemini 2.0 Flash）与较小模型（Gemini 2.0 Flash-Lite）相比所获得的性能提升的散点图和趋势线，这些提升是（左）平均上下文长度和（右）平均输出长度（与图 4 中的数值相同）的函数。

The Effect of Context Length and Required Thinking: The tasks in BBEH come at different average context lengths (see Figure [3](https://arxiv.org/html/2502.19187v2#S4.F3 "Figure 3 ‣ 4 BIG-Bench Extra Hard ‣ BIG-Bench Extra Hard")) and may require different amount of thinking (as shown using the output length proxy in Figure [4](https://arxiv.org/html/2502.19187v2#S5.F4 "Figure 4 ‣ 5.1 BBEH Analysis ‣ 5 Results and Analyses ‣ BIG-Bench Extra Hard")). We use this property to understand the effect of context length and required thinking on reasoning vs general models, and on larger vs smaller models. To this end, in Figure [7](https://arxiv.org/html/2502.19187v2#S5.F7 "Figure 7 ‣ 5.3 Further Analyses of the Results ‣ 5 Results and Analyses ‣ BIG-Bench Extra Hard") we compare the performance of o3-mini (high) vs GPT4o and Gemini 2.0 Flash vs Gemini 2.0 Flash-Lite as a function of average context lengths of the tasks and average output length as a proxy for required thinking44We removed the _Shuffled Objects_ task for this analysis as some models ran out of effective tokens and started degenerating, and this was adding noise to the analysis.  
在此次分析中，我们移除了"乱序对象"任务，因为部分模型耗尽了有效标记并开始性能退化，这给分析带来了干扰。  
上下文长度与所需思考量的影响：BBEH 中的任务具有不同的平均上下文长度（见图 3），并且可能需要不同程度的思考量（如图 4 中通过输出长度代理指标所示）。我们利用这一特性来探究上下文长度和所需思考量对推理模型与通用模型、以及大型模型与小型模型的影响。为此，在图 7 中，我们比较了 o3-mini（高配版）与 GPT4o、以及 Gemini 2.0 Flash 与 Gemini 2.0 Flash-Lite 的性能表现，将其作为任务平均上下文长度和平均输出长度（作为所需思考量的代理指标）的函数进行分析。. We observe that the gains of o3-mini tend to increase compared to GPT4o both when context length increases and when the required thinking increases, showing how reasoning models may have improved across both directions compared to general models. For Gemini 2.0 Flash vs Gemini 2.0 Flash-Lite, we see a similar increase in gains when the context length increases, but the curve for the case of increased thinking remains mostly flat.  
我们观察到，当上下文长度增加或所需思考量增加时，o3-mini 相较于 GPT4o 的优势往往更为显著，这表明推理模型在这两个维度上相比通用模型可能具有更强的适应性。对于 Gemini 2.0 Flash 与 Gemini 2.0 Flash-Lite 的比较，在上下文长度增加时我们也看到了类似的优势扩大趋势，但在思考量增加的情况下，性能曲线基本保持平稳。

## 6Conclusion  6 结论

Recent advances in LLM reasoning has made these models reach near ceiling performance on existing general reasoning benchmarks such as BIG-Bench and its harder variant BBH, and shifted focus toward other types of more focused reasoning. However, substantial distance remains before we can claim these models posses true mastery of diverse reasoning skills. To rekindle the pursuit of truly robust and versatile LLM reasoners, we presented BIG-Bench Extra Hard (BBEH), a significantly more challenging successor to BBH. This new benchmark, meticulously crafted to amplify the difficulty of existing tasks while preserving their core diversity, reveals a stark reality: even the most advanced LLMs still grapple with fundamental aspects of general reasoning. BBEH provides a crucial stepping stone, reigniting the challenge and offering a more rigorous platform for future research aimed at unlocking the full potential of LLMs in complex, real-world applications.  
随着 LLM 推理能力的近期突破，这些模型在现有通用推理基准测试（如 BIG-Bench 及其困难变体 BBH）上已接近性能天花板，研究焦点已转向其他更专业的推理类型。然而，要宣称这些模型真正掌握了多样化的推理技能，仍有相当长的距离。为重新激发对真正稳健且多才多艺的 LLM 推理器的追求，我们推出了 BIG-Bench Extra Hard（BBEH）——这是 BBH 更具挑战性的继承者。这个新基准经过精心设计，在保持核心多样性的同时显著提升了现有任务的难度，揭示了一个严峻现实：即使最先进的 LLM 仍在通用推理的基本层面挣扎。BBEH 提供了关键性的进阶台阶，重新点燃了挑战，并为未来研究提供了更严谨的平台，旨在释放 LLM 在复杂现实应用中的全部潜力。

## Acknowledgements  致谢

We acknowledge the help from Vahab Mirrokni, Tania Bedrax-Weiss, Don Metzler, Javad Hosseini, Phoebe Kirk, and Katherine Tong.  
我们感谢 Vahab Mirrokni、Tania Bedrax-Weiss、Don Metzler、Javad Hosseini、Phoebe Kirk 和 Katherine Tong 的帮助。

## References

- Achiam et al. (2023)J. Achiam, S. Adler, S. Agarwal, L. Ahmad, I. Akkaya, F. L. Aleman, D. Almeida, J. Altenschmidt, S. Altman, S. Anadkat, et al.Gpt-4 technical report._arXiv preprint arXiv:2303.08774_, 2023.
- Anil et al. (2023)R. Anil, A. M. Dai, O. Firat, M. Johnson, D. Lepikhin, A. Passos, S. Shakeri, E. Taropa, P. Bailey, Z. Chen, E. Chu, J. H. Clark, L. E. Shafey, Y. Huang, K. Meier-Hellstern, G. Mishra, E. Moreira, M. Omernick, K. Robinson, S. Ruder, Y. Tay, K. Xiao, Y. Xu, Y. Zhang, G. H. Abrego, J. Ahn, J. Austin, P. Barham, J. Botha, J. Bradbury, S. Brahma, K. Brooks, M. Catasta, Y. Cheng, C. Cherry, C. A. Choquette-Choo, A. Chowdhery, C. Crepy, S. Dave, M. Dehghani, S. Dev, J. Devlin, M. Díaz, N. Du, E. Dyer, V. Feinberg, F. Feng, V. Fienber, M. Freitag, X. Garcia, S. Gehrmann, L. Gonzalez, G. Gur-Ari, S. Hand, H. Hashemi, L. Hou, J. Howland, A. Hu, J. Hui, J. Hurwitz, M. Isard, A. Ittycheriah, M. Jagielski, W. Jia, K. Kenealy, M. Krikun, S. Kudugunta, C. Lan, K. Lee, B. Lee, E. Li, M. Li, W. Li, Y. Li, J. Li, H. Lim, H. Lin, Z. Liu, F. Liu, M. Maggioni, A. Mahendru, J. Maynez, V. Misra, M. Moussalem, Z. Nado, J. Nham, E. Ni, A. Nystrom, A. Parrish, M. Pellat, M. Polacek, A. Polozov, R. Pope, S. Qiao, E. Reif, B. Richter, P. Riley, A. C. Ros, A. Roy, B. Saeta, R. Samuel, R. Shelby, A. Slone, D. Smilkov, D. R. So, D. Sohn, S. Tokumine, D. Valter, V. Vasudevan, K. Vodrahalli, X. Wang, P. Wang, Z. Wang, T. Wang, J. Wieting, Y. Wu, K. Xu, Y. Xu, L. Xue, P. Yin, J. Yu, Q. Zhang, S. Zheng, C. Zheng, W. Zhou, D. Zhou, S. Petrov, and Y. Wu.Palm 2 technical report, 2023.URL [https://arxiv.org/abs/2305.10403](https://arxiv.org/abs/2305.10403).
- Bansal and Maini (2024)H. Bansal and P. Maini.Peeking behind closed doors: Risks of llm evaluation by private data curators.2024.URL [https://pratyushmaini.github.io/blog/2024/risks-private-evals/](https://pratyushmaini.github.io/blog/2024/risks-private-evals/).
- Beniwal et al. (2024)H. Beniwal, M. Singh, et al.Remember this event that year? assessing temporal information and reasoning in large language models._arXiv preprint arXiv:2402.11997_, 2024.
- Bohnet et al. (2024)B. Bohnet, A. Nova, A. T. Parisi, K. Swersky, K. Goshvadi, H. Dai, D. Schuurmans, N. Fiedel, and H. Sedghi.Exploring and benchmarking the planning capabilities of large language models, 2024.URL [https://arxiv.org/abs/2406.13094](https://arxiv.org/abs/2406.13094).
- Cobbe et al. (2021)K. Cobbe, V. Kosaraju, M. Bavarian, M. Chen, H. Jun, L. Kaiser, M. Plappert, J. Tworek, J. Hilton, R. Nakano, et al.Training verifiers to solve math word problems._arXiv preprint arXiv:2110.14168_, 2021.
- Dhingra et al. (2022)B. Dhingra, J. R. Cole, J. M. Eisenschlos, D. Gillick, J. Eisenstein, and W. W. Cohen.Time-aware language models as temporal knowledge bases._Transactions of the Association for Computational Linguistics_, 10:257–273, 2022.
- Dubey et al. (2024)A. Dubey, A. Jauhri, A. Pandey, A. Kadian, A. Al-Dahle, A. Letman, A. Mathur, A. Schelten, A. Yang, A. Fan, et al.The llama 3 herd of models._arXiv preprint arXiv:2407.21783_, 2024.
- Fatemi et al. (2024)B. Fatemi, M. Kazemi, A. Tsitsulin, K. Malkan, J. Yim, J. Palowitch, S. Seo, J. Halcrow, and B. Perozzi.Test of time: A benchmark for evaluating llms on temporal reasoning._arXiv preprint arXiv:2406.09170_, 2024.
- Glazer et al. (2024)E. Glazer, E. Erdil, T. Besiroglu, D. Chicharro, E. Chen, A. Gunning, C. F. Olsson, J.-S. Denain, A. Ho, E. de Oliveira Santos, O. Järviniemi, M. Barnett, R. Sandler, M. Vrzala, J. Sevilla, Q. Ren, E. Pratt, L. Levine, G. Barkley, N. Stewart, B. Grechuk, T. Grechuk, S. V. Enugandla, and M. Wildon.Frontiermath: A benchmark for evaluating advanced mathematical reasoning in ai, 2024.URL [https://arxiv.org/abs/2411.04872](https://arxiv.org/abs/2411.04872).
- Guo et al. (2025)D. Guo, D. Yang, H. Zhang, J. Song, R. Zhang, R. Xu, Q. Zhu, S. Ma, P. Wang, X. Bi, et al.Deepseek-r1: Incentivizing reasoning capability in llms via reinforcement learning._arXiv preprint arXiv:2501.12948_, 2025.
- Halpern (2008)J. Y. Halpern.Defaults and normality in causal structures.In _KR_, pages 198–208, 2008.
- Halpern (2016)J. Y. Halpern._Actual Causality_.The MIT Press, 2016.
- Halpern and Hitchcock (2015)J. Y. Halpern and C. Hitchcock.Graded causation and defaults._The British Journal for the Philosophy of Science_, 2015.
- Hendrycks et al. (2020)D. Hendrycks, C. Burns, S. Basart, A. Zou, M. Mazeika, D. Song, and J. Steinhardt.Measuring massive multitask language understanding._arXiv preprint arXiv:2009.03300_, 2020.
- Hessel et al. (2022)J. Hessel, A. Marasović, J. D. Hwang, L. Lee, J. Da, R. Zellers, R. Mankoff, and Y. Choi.Do androids laugh at electric sheep? humor" understanding" benchmarks from the new yorker caption contest._arXiv preprint arXiv:2209.06293_, 2022.
- Hosseini et al. (2024)A. Hosseini, A. Sordoni, D. Toyama, A. Courville, and R. Agarwal.Not all llm reasoners are created equal._arXiv preprint arXiv:2410.01748_, 2024.
- Icard et al. (2017)T. F. Icard, J. F. Kominsky, and J. Knobe.Normality and actual causal strength._Cognition_, 161:80–93, 2017.
- Kazemi et al. (2023a)M. Kazemi, H. Alvari, A. Anand, J. Wu, X. Chen, and R. Soricut.Geomverse: A systematic evaluation of large models for geometric reasoning._arXiv preprint arXiv:2312.12241_, 2023a.
- Kazemi et al. (2023b)M. Kazemi, Q. Yuan, D. Bhatia, N. Kim, X. Xu, V. Imbrasaite, and D. Ramachandran.Boardgameqa: A dataset for natural language reasoning with contradictory information._Advances in Neural Information Processing Systems_, 36, 2023b.
- Kazemi et al. (2024)M. Kazemi, N. Dikkala, A. Anand, P. Devic, I. Dasgupta, F. Liu, B. Fatemi, P. Awasthi, D. Guo, S. Gollapudi, et al.Remi: A dataset for reasoning with multiple images._arXiv preprint arXiv:2406.09175_, 2024.
- Khodak et al. (2017)M. Khodak, N. Saunshi, and K. Vodrahalli.A large self-annotated corpus for sarcasm._arXiv preprint arXiv:1704.05579_, 2017.
- Kıcıman et al. (2023)E. Kıcıman, R. Ness, A. Sharma, and C. Tan.Causal reasoning and large language models: Opening a new frontier for causality._arXiv preprint arXiv:2305.00050_, 2023.
- Kominsky et al. (2015)J. F. Kominsky, J. Phillips, T. Gerstenberg, D. Lagnado, and J. Knobe.Causal superseding._Cognition_, 137:196–209, 2015.
- Kueffner (2021)K. R. Kueffner.A comprehensive survey of the actual causality literature.2021.
- (26)lmarena.Chatbot Arena Leaderboard - a Hugging Face Space by lmarena-ai — huggingface.co.[https://huggingface.co/spaces/lmarena-ai/chatbot-arena-leaderboard](https://huggingface.co/spaces/lmarena-ai/chatbot-arena-leaderboard).
- Lu et al. (2023)P. Lu, H. Bansal, T. Xia, J. Liu, C. Li, H. Hajishirzi, H. Cheng, K.-W. Chang, M. Galley, and J. Gao.Mathvista: Evaluating mathematical reasoning of foundation models in visual contexts._arXiv preprint arXiv:2310.02255_, 2023.
- McKenzie et al. (2023)I. R. McKenzie, A. Lyzhov, M. Pieler, A. Parrish, A. Mueller, A. Prabhu, E. McLean, A. Kirtland, A. Ross, A. Liu, et al.Inverse scaling: When bigger isn’t better._arXiv preprint arXiv:2306.09479_, 2023.
- Miner et al. (2024)S. Miner, Y. Takashima, S. Han, F. Erata, T. Antonopoulos, R. Piskac, and S. J. Shapiro.Scheherazade: Evaluating chain-of-thought math reasoning in llms with chain-of-problems._arXiv preprint arXiv:2410.00151_, 2024.
- Mirzadeh et al. (2024)I. Mirzadeh, K. Alizadeh, H. Shahrokhi, O. Tuzel, S. Bengio, and M. Farajtabar.Gsm-symbolic: Understanding the limitations of mathematical reasoning in large language models._arXiv preprint arXiv:2410.05229_, 2024.
- Mirzaee et al. (2021)R. Mirzaee, H. R. Faghihi, Q. Ning, and P. Kordjmashidi.Spartqa:: A textual question answering benchmark for spatial reasoning._arXiv preprint arXiv:2104.05832_, 2021.
- Nie et al. (2023)A. Nie, Y. Zhang, A. S. Amdekar, C. Piech, T. B. Hashimoto, and T. Gerstenberg.MoCa: Measuring human-language model alignment on causal and moral judgment tasks.In _Advances in Neural Information Processing Systems_, pages 78360–78393, 2023.
- Parmar et al. (2024)M. Parmar, N. Patel, N. Varshney, M. Nakamura, M. Luo, S. Mashetty, A. Mitra, and C. Baral.Logicbench: Towards systematic evaluation of logical reasoning ability of large language models.In _Proceedings of the 62nd Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers)_, pages 13679–13707, 2024.
- Phan et al. (2025)L. Phan, A. Gatti, Z. Han, and N. L. et. al.Humanity’s last exam, 2025.URL [https://arxiv.org/abs/2501.14249](https://arxiv.org/abs/2501.14249).
- Phillips et al. (2015)J. Phillips, J. B. Luguri, and J. Knobe.Unifying morality’s influence on non-moral judgments: The relevance of alternative possibilities._Cognition_, 145:30–42, 2015.
- Romanou et al. (2023)A. Romanou, S. Montariol, D. Paul, L. Laugier, K. Aberer, and A. Bosselut.CRAB: Assessing the strength of causal relationships between real-world events._arXiv preprint arXiv:2311.04284_, 2023.
- Sakaguchi et al. (2021)K. Sakaguchi, R. L. Bras, C. Bhagavatula, and Y. Choi.Winogrande: An adversarial winograd schema challenge at scale._Communications of the ACM_, 64(9):99–106, 2021.
- Sánchez et al. (2024)E. Sánchez, B. Alastruey, C. Ropers, P. Stenetorp, M. Artetxe, and M. R. Costa-jussà.Linguini: A benchmark for language-agnostic linguistic reasoning._arXiv preprint arXiv:2409.12126_, 2024.
- Saparov and He (2022)A. Saparov and H. He.Language models are greedy reasoners: A systematic formal analysis of chain-of-thought._arXiv preprint arXiv:2210.01240_, 2022.
- Saparov et al. (2023)A. Saparov, R. Y. Pang, V. Padmakumar, N. Joshi, M. Kazemi, N. Kim, and H. He.Testing the general deductive reasoning capacity of large language models using ood examples._Advances in Neural Information Processing Systems_, 36:3083–3105, 2023.
- Saparov et al. (2024)A. Saparov, S. Pawar, S. Pimpalgaonkar, N. Joshi, R. Y. Pang, V. Padmakumar, S. M. Kazemi, N. Kim, and H. He.Transformers struggle to learn to search._arXiv preprint arXiv:2412.04703_, 2024.
- (42)ScaleAI.SEAL LLM Leaderboards: Expert-Driven Private Evaluations — scale.com.[https://scale.com/leaderboard](https://scale.com/leaderboard).
- Shah et al. (2024)K. Shah, N. Dikkala, X. Wang, and R. Panigrahy.Causal language modeling can elicit search and reasoning capabilities on logic puzzles._arXiv preprint arXiv:2409.10502_, 2024.
- Shi et al. (2022)Z. Shi, Q. Zhang, and A. Lipani.Stepgame: A new benchmark for robust multi-hop spatial reasoning in texts.In _Proceedings of the AAAI conference on artificial intelligence_, volume 36, pages 11321–11329, 2022.
- Srivastava et al. (2022)A. Srivastava, A. Rastogi, A. Rao, A. A. M. Shoeb, A. Abid, A. Fisch, A. R. Brown, A. Santoro, A. Gupta, A. Garriga-Alonso, et al.Beyond the imitation game: Quantifying and extrapolating the capabilities of language models._arXiv preprint arXiv:2206.04615_, 2022.
- Suzgun et al. (2022)M. Suzgun, N. Scales, N. Schärli, S. Gehrmann, Y. Tay, H. W. Chung, A. Chowdhery, Q. V. Le, E. H. Chi, D. Zhou, et al.Challenging big-bench tasks and whether chain-of-thought can solve them._arXiv preprint arXiv:2210.09261_, 2022.
- Tafjord et al. (2020)O. Tafjord, B. D. Mishra, and P. Clark.Proofwriter: Generating implications, proofs, and abductive statements over natural language._arXiv preprint arXiv:2012.13048_, 2020.
- Talmor et al. (2018)A. Talmor, J. Herzig, N. Lourie, and J. Berant.Commonsenseqa: A question answering challenge targeting commonsense knowledge._arXiv preprint arXiv:1811.00937_, 2018.
- Team et al. (2024a)G. Team, P. Georgiev, V. I. Lei, R. Burnell, L. Bai, A. Gulati, G. Tanzer, D. Vincent, Z. Pan, S. Wang, et al.Gemini 1.5: Unlocking multimodal understanding across millions of tokens of context._arXiv preprint arXiv:2403.05530_, 2024a.
- Team et al. (2024b)G. Team, M. Riviere, S. Pathak, P. G. Sessa, C. Hardin, S. Bhupatiraju, L. Hussenot, T. Mesnard, B. Shahriari, A. Ramé, et al.Gemma 2: Improving open language models at a practical size._arXiv preprint arXiv:2408.00118_, 2024b.
- Team et al. (2025)G. Team, A. Kamath, J. Ferret, S. Pathak, N. Vieillard, R. Merhej, S. Perrin, T. Matejovicova, A. Ramé, M. Rivière, et al.Gemma 3 technical report._arXiv preprint arXiv:2503.19786_, 2025.
- Tyen et al. (2023)G. Tyen, H. Mansoor, P. Chen, T. Mak, and V. Cărbune.LLMs cannot find reasoning errors, but can correct them!_arXiv preprint arXiv:2311.08516_, 2023.
- Tyen et al. (2024)G. Tyen, H. Mansoor, V. Carbune, P. Chen, and T. Mak.LLMs cannot find reasoning errors, but can correct them given the error location.In L.-W. Ku, A. Martins, and V. Srikumar, editors, _Findings of the Association for Computational Linguistics: ACL 2024_, pages 13894–13908, Bangkok, Thailand, Aug. 2024. Association for Computational Linguistics.[10.18653/v1/2024.findings-acl.826](https://arxiv.org/doi.org/10.18653/v1/2024.findings-acl.826).URL [https://aclanthology.org/2024.findings-acl.826/](https://aclanthology.org/2024.findings-acl.826/).
- Vodrahalli et al. (2024)K. Vodrahalli, S. Ontanon, N. Tripuraneni, K. Xu, S. Jain, R. Shivanna, J. Hui, N. Dikkala, M. Kazemi, B. Fatemi, et al.Michelangelo: Long context evaluations beyond haystacks via latent structure queries._arXiv preprint arXiv:2409.12640_, 2024.
- Wang (2018)A. Wang.Glue: A multi-task benchmark and analysis platform for natural language understanding._arXiv preprint arXiv:1804.07461_, 2018.
- Wang et al. (2019)A. Wang, Y. Pruksachatkun, N. Nangia, A. Singh, J. Michael, F. Hill, O. Levy, and S. Bowman.Superglue: A stickier benchmark for general-purpose language understanding systems._Advances in neural information processing systems_, 32, 2019.
- Wang et al. (2024)Y. Wang, X. Ma, G. Zhang, Y. Ni, A. Chandra, S. Guo, W. Ren, A. Arulraj, X. He, Z. Jiang, et al.Mmlu-pro: A more robust and challenging multi-task language understanding benchmark._arXiv preprint arXiv:2406.01574_, 2024.
- Weston et al. (2015)J. Weston, A. Bordes, S. Chopra, A. M. Rush, B. Van Merriënboer, A. Joulin, and T. Mikolov.Towards ai-complete question answering: A set of prerequisite toy tasks._arXiv preprint arXiv:1502.05698_, 2015.
- White et al. (2024)C. White, S. Dooley, M. Roberts, A. Pal, B. Feuer, S. Jain, R. Shwartz-Ziv, N. Jain, K. Saifullah, S. Naidu, et al.Livebench: A challenging, contamination-free llm benchmark._arXiv preprint arXiv:2406.19314_, 2024.
- Xia et al. (2024)H. Xia, Z. Yang, Y. Wang, R. Tracy, Y. Zhao, D. Huang, Z. Chen, Y. Zhu, Y.-f. Wang, and W. Shen.Sportqa: A benchmark for sports understanding in large language models._arXiv preprint arXiv:2402.15862_, 2024.
- Xiong et al. (2024)S. Xiong, A. Payani, R. Kompella, and F. Fekri.Large language models can learn temporal reasoning._arXiv preprint arXiv:2401.06853_, 2024.
- Yamada et al. (2023)Y. Yamada, Y. Bao, A. K. Lampinen, J. Kasai, and I. Yildirim.Evaluating spatial understanding of large language models._arXiv preprint arXiv:2310.14540_, 2023.
- Yang et al. (2024a)A. Yang, B. Yang, B. Zhang, B. Hui, B. Zheng, B. Yu, C. Li, D. Liu, F. Huang, H. Wei, et al.Qwen2. 5 technical report._arXiv preprint arXiv:2412.15115_, 2024a.
- Yang et al. (2024b)Z. Yang, H. Xia, J. Li, Z. Chen, Z. Zhu, and W. Shen.Sports intelligence: Assessing the sports understanding capabilities of language models through question answering from text to video._arXiv preprint arXiv:2406.14877_, 2024b.
- Zellers et al. (2019)R. Zellers, A. Holtzman, Y. Bisk, A. Farhadi, and Y. Choi.Hellaswag: Can a machine really finish your sentence?, 2019.
- Zhang et al. (2024)J. Zhang, L. Jain, Y. Guo, J. Chen, K. L. Zhou, S. Suresh, A. Wagenmaker, S. Sievert, T. Rogers, K. Jamieson, R. Mankoff, and R. Nowak.Humor in ai: Massive scale crowd-sourced preferences and benchmarks for cartoon captioning, 2024.URL [https://arxiv.org/abs/2406.10522](https://arxiv.org/abs/2406.10522).

|   |   |   |   |   |   |   |   |   |   |   |   |   |   |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|Models|Random  随机|Qwen-2.5-7B-Instruct|Llama 3.1 8b Instruct  Llama 3.1 8b 指令版|Gemma2 27b IT|Gemma3 4b|Gemma3 12b|Gemma3 27b|Gemini 2.0 Flash-Lite  双子座 2.0 闪亮轻量版|Gemini 2.0 Flash  双子座 2.0 闪存版|GPT4o|Distill R1 Qwen 32b  蒸馏 R1 Qwen 32b|DeepSeek R1|o3-mini (high)|
|BBEH(Micro Average)|8.4|12.5|10.6|14.8|11.0|16.3|18.8|19.7|23.9|22.3|19.2|34.9|54.2|

Table 4:The micro average performance of various models on BBEH.  
表 4：各模型在 BBEH 上的微平均性能。

## Appendix ADetailed Description of the Tasks and Task-Specific Insights from Experiments  
附录 A 任务详细说明及实验中的任务特定见解

Here, we describe in detail how each of the 23 new tasks in BBEH have been created. Moreover, we provide interesting task-specific insights from our experiments.  
在此，我们详细介绍了 BBEH 中 23 个新任务是如何创建的。此外，我们还提供了实验中获得的具有启发性的任务特定见解。

|   |   |   |   |   |   |   |
|---|---|---|---|---|---|---|
|Models  模型|Gemma2 27b IT|Gemini 2.0 Flash-Lite  双子座 2.0 闪亮轻量版|Gemini 2.0 Flash  双子座 2.0 闪存版|GPT4o|DeepSeek R1|o3-mini (high)  o3-mini（高）|
|Unknown %  未知|77.6|67.4|73.3|82.4|39.7|65.5|

Table 5:Percentage of _unknown_ predictions on BoardgameQA for different models (only one third of the labels are _unknown_).  
表 5：不同模型在 BoardgameQA 上的未知预测百分比（仅三分之一标签为未知）。

### A.1BoardgameQA  A.1 棋盘游戏问答

BoardgameQA (Kazemi et al., [2023b](https://arxiv.org/html/2502.19187v2#bib.bib20)) is a benchmark where given a defeasible theory (a set of input facts, possibly contradictory rules, and preferences over the rules), and a question about that theory, the task is to do multi-hop reasoning and conflict resolution over the input theory to answer the question. The final answer to the question is either ‘proved‘ (if the statement in the question derives from the theory), ‘disproved‘ (if the negation of the statement in the question derives from the theory), or ‘unknown‘ (if neither the statement in the questions nor its negation derives from the theory). With three labels per question, a random baseline has an accuracy of  33.3%. Conflicts may arise when two rules such as R⁢1:a→c and R⁢2:b→¬c are both activated leading to different beliefs about the truth value of the variable c. However, preferences over the rules is provided in the input question and in the case of conflicts, the derivation from the rule with the higher preference must be concluded (e.g., if R⁢1 is preferred over R⁢2 and they both apply, then we conclude c is true).  
BoardgameQA（Kazemi 等人，2023b）是一个基准测试，其中给定一个可废止理论（一组输入事实、可能矛盾的规则以及规则间的偏好），以及关于该理论的问题，任务是对输入理论进行多跳推理和冲突解决以回答问题。问题的最终答案要么是“已证明”（如果问题中的陈述可从理论推导出），要么是“已证伪”（如果问题中陈述的否定可从理论推导出），要么是“未知”（如果问题中的陈述及其否定均无法从理论推导出）。每个问题有三个标签，随机基线的准确率为 33.3%。当两个规则如 R⁢1:a→c 和 R⁢2:b→¬c 同时被激活，导致对变量 c 的真值产生不同信念时，可能会产生冲突。然而，输入问题中提供了规则间的偏好，在发生冲突的情况下，必须根据偏好较高的规则进行推导（例如，如果 R⁢1 比 R⁢2 更受偏好且两者均适用，则我们得出结论 c 为真）。

One of the parameters controlling the difficulty of the problems in this benchmark is the depth, corresponding to the number of hops of reasoning that must be done to compute the truth value of the statement in the question. We use the code from the paper and generate tasks with depths 6, 7 and 8. We made some changes in the prompt to clarify the task for the model so that it works in zero-shot setting. That includes: _Answer ’proved’ if it can be proved, ’disproved’ if it can be disproved, and ’unknown’ if it can neither be proved nor disproved_ as well as _A rule is only applicable if all of its antecedents can be proved._. We then uniformly sampled prompts across depths and labels to created the final set.  
控制本基准测试中问题难度的参数之一是深度，它对应于计算问题陈述真值所需进行的推理跳数。我们使用论文中的代码，生成了深度为 6、7 和 8 的任务。我们对提示语进行了一些修改，以向模型阐明任务要求，使其能够在零样本设置下工作。这些修改包括：如果可以证明，则回答“已证明”；如果可以证伪，则回答“已证伪”；如果既不能证明也不能证伪，则回答“未知”；以及一条规则仅在其所有前提条件都能被证明时才适用。然后，我们均匀地从不同深度和标签中采样提示语，创建了最终的数据集。

Through analyzing the model outputs, we observe that for this task, models tend to over-predict that the truth value of a statement is _unknown_. The percentage of _unknown_ predictions for our models (when at least one of the three labels was predicted) is presented in Table [5](https://arxiv.org/html/2502.19187v2#A1.T5 "Table 5 ‣ Appendix A Detailed Description of the Tasks and Task-Specific Insights from Experiments ‣ BIG-Bench Extra Hard"). Note that only one-third of the problems have an _unknown_ label. An _unknown_ label is typically predicted when the model cannot find a way to either prove or disprove the statement from the facts and rules. Therefore, we observe a failure mode for the state-of-the-art models: they struggle to search the space of facts and rules and find a proof, despite there being one. While similar observations have been previously made about models without chain-of-thought (Saparov et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib41)), our results apply to the case with chain-of-thought.  
通过分析模型输出，我们观察到在此任务中，模型倾向于过度预测陈述的真值为未知。表 5 展示了我们模型预测为未知的百分比（当至少预测了三个标签之一时）。请注意，只有三分之一的问题具有未知标签。当模型无法从事实和规则中找到证明或反驳陈述的方法时，通常会预测未知标签。因此，我们观察到最先进模型存在一种失败模式：尽管存在证明，它们仍难以在事实和规则空间中搜索并找到证明。虽然先前已有关于无思维链模型的类似观察（Saparov 等人，2024），但我们的结果适用于带有思维链的情况。

### A.2Boolean Expressions  A.2 布尔表达式

This task requires determining the truth value of a statement that is composed of logical operands such as T⁢r⁢u⁢e and F⁢a⁢l⁢s⁢e as well as other textual or mathematical statements that evaluate to True or False. To create this task, we first randomly create expressions containing only True and False operands and three logical operators: _and_, _or_, and _not_. We create this in a bottom-up fashion where we generate smaller sub-expressions and then combine them with logical operators. Once a large enough expression is created, we replace some of the T⁢r⁢u⁢e and F⁢a⁢l⁢s⁢e operands with statements that evaluate to True or False. These could be mathematical expressions such as 24 - 2 is greater than 48 / 2 (which evaluates to False) or textual statements such as The capital of Canada is Ottawa (which evaluates to True). In both cases, we select these statements from a predefined set. While determining the truth value of each of these statements in isolation may be easy for many models, including these statements makes it more difficult for models; otherwise, they can simply solve the problem by generating a single line of python code.  
本任务要求判断一个由逻辑操作数（如 T⁢r⁢u⁢e 和 F⁢a⁢l⁢s⁢e ）以及其他可评估为真或假的文本或数学陈述所构成的语句的真值。为创建此任务，我们首先随机生成仅包含真与假操作数以及三种逻辑运算符（与、或、非）的表达式。我们采用自底向上的方式构建：先生成较小的子表达式，再用逻辑运算符将它们组合起来。当生成足够大的表达式后，我们将部分 T⁢r⁢u⁢e 和 F⁢a⁢l⁢s⁢e 操作数替换为可评估为真或假的陈述。这些陈述可以是数学表达式（例如“24 减 2 大于 48 除以 2”——评估结果为假），也可以是文本陈述（例如“加拿大的首都是渥太华”——评估结果为真）。在这两种情况下，我们都从预定义的集合中选择这些陈述。虽然对于许多模型而言，单独判断每个陈述的真值可能很容易，但包含这些陈述会增加模型的难度；否则，它们只需生成一行 Python 代码即可解决问题。

We generate five expressions using the approach outlined above, four of which evaluate to False and one of which evaluate to True. The job of the model is then to find the expression that evaluates to True. Since this is a five-way question, the random chance accuracy is 20%.  
我们采用上述方法生成了五个表达式，其中四个结果为假，一个结果为真。模型的任务是找出结果为真的表达式。由于这是一个五选一的问题，随机猜测的准确率为 20%。

### A.3Buggy Tables  A.3 有缺陷的表格

The objective in this task is to be able to respond to conditional queries over tabular data, where the information in the table are presented in a buggy way but the description for the bug is also presented so that the model can reconstruct the original table based on that. As an example, we provide a row-major/column-major format of the table where the null values have been mistakenly removed, but we also provide the positions of the null values in the original table so one can reconstruct the table given the two pieces of information. As another example, we provide a buggy version of the table where some random values are appended at the end of each row or each column, but we also specify how they have been added so one can use this information to remove them and reconstruct the original table. As yet another example, we provide a markdown format of the table that mixes each two rows of the table into one row, but also provide an explanation of how each two rows have been merged into one so that the original table can be reconstructed based on that information. Examples of conditional queries include computing some statistics (count, sum, mean, stdev, median) of some columns while only considering rows where some columns have some specific values.  
本任务的目标是能够对表格数据进行条件查询，其中表格信息以存在错误的方式呈现，但同时也提供了错误描述，以便模型能够基于此重建原始表格。例如，我们提供一个行优先/列优先格式的表格，其中空值被错误地移除，但我们也提供了原始表格中空值的位置，因此可以根据这两条信息重建表格。再如，我们提供一个存在错误的表格版本，其中每行或每列的末尾附加了一些随机值，但我们也说明了这些值是如何添加的，因此可以利用此信息移除它们并重建原始表格。又如，我们提供一个表格的 Markdown 格式，其中将表格的每两行合并为一行，但也解释了每两行是如何合并的，以便基于此信息重建原始表格。 条件查询的示例包括：在仅考虑某些列具有特定值的行时，计算某些列的统计信息（计数、总和、均值、标准差、中位数）。

|   |   |   |   |
|---|---|---|---|
|Ex. ID  示例 ID|Input  输入|Output  输出|Gemini 2.0 Flash Response  <br>Gemini 2.0 Flash 响应|
|36|Question: Suzy and Billy are working on a project that is very important for our nation’s security. The boss tells them both: “Be sure that you are here at exactly 9 am. It is absolutely essential that you arrive at that time.” Both Billy and Suzy arrive at 9 am. As it happens, there was a motion detector installed in the room where they arrived. The motion detector was set up to be triggered if at least one person appeared in the room at the same time. So the motion detector went off. Did Billy cause the motion detector to go off? Reply Yes or No based on the answer the majority of people would give. If you think people would be split roughly 50-50 between Yes and No then reply Ambiguous.  <br>问题：苏西和比利正在做一个对我们国家安全至关重要的项目。老板告诉他们俩："一定要在上午 9 点准时到这里。你们必须在这个时间到达。" 比利和苏西都在上午 9 点到达。碰巧的是，他们到达的房间里安装了一个运动探测器。这个运动探测器被设置为如果至少有一人同时出现在房间里就会触发。所以运动探测器响了。是比利导致运动探测器响的吗？根据大多数人会给出的答案回答是或否。如果你认为人们会大致在是和否之间各占一半，那么回答模棱两可。|Ambiguous  模棱两可|The question asks whether Billy caused the motion detector to go off. The motion detector was triggered if at least one person was present. Both Billy and Suzy were present at 9 am. Suzy’s presence also triggered the motion detector. Since the motion detector would have gone off regardless of whether Billy was there, it cannot be definitively said that Billy caused the motion detector to go off. The answer is: Ambiguous.  <br>问题问的是比利是否导致运动探测器响了。运动探测器在至少有一人在场时触发。比利和苏西都在上午 9 点在场。苏西的出现也触发了运动探测器。由于无论比利是否在场，运动探测器都会响，所以不能明确地说比利导致运动探测器响了。答案是：模棱两可。|
|123|Question: A group of students who lived on the same floor of a dormitory obtained a copy of the final exam for their biology class. The students cheated on the test. One student, John Granger, did not go along with the group. Granger deviates from the norm and refuses to cheat on the test. The biology class comprises 80 students and is graded on a curve such that 20 people will receive a grade of A, 20 a grade of B, 20 a grade of C, and 20 students will receive a D. Grangerś score was the 20th-highest score in the class, which means he was the last student to receive a grade of A. The 21st student was a pre-med student who received a B and, as a result, missed the GPA cutoff she needed to get into the medical school she was hoping for by .07 GPA points. Did Granger cause the student to fail to meet the medical school cutoff? Reply Yes or No based on the answer the majority of people would give. If you think people would be split roughly 50-50 between Yes and No then reply Ambiguous.  <br>问题：一群住在宿舍同一层的学生拿到了他们生物课的期末考试试卷。这些学生在考试中作弊。其中一名学生约翰·格兰杰没有参与其中。格兰杰违背常规，拒绝在考试中作弊。生物课共有 80 名学生，成绩按曲线评分，即 20 人得 A，20 人得 B，20 人得 C，20 人得 D。格兰杰的成绩是班级第 20 名，这意味着他是最后一个得 A 的学生。第 21 名学生是一名医学预科生，她得了 B，结果因此以 0.07 个绩点的差距未能达到她希望进入的医学院的绩点要求。格兰杰是否导致该学生未能达到医学院的录取标准？根据大多数人会给出的答案回答“是”或“否”。如果你认为人们会大致在“是”和“否”之间各占一半，则回答“模糊”。|No  不|Here’s a step-by-step analysis: 1. John’s Score: John earned the 20th highest score, placing him at the very top of the “A" grade range. 2. The Pre-Med Student’s Score: The pre-med student scored the 21st highest score, placing her at the top of the “B" grade range. 3. Impact on the Curve: If John had cheated and scored higher, he could have potentially been in the “A" range with a higher score. This would have potentially shifted the scores on the curve down. 4. The Student’s Failure: It is possible, though not guaranteed, that if John had cheated and scored higher, the curve could have shifted down. 5. Conclusion: The pre-med student failing the cutoff is related to the grading curve. If a number of students cheated, it changed the overall distribution. It is highly probable that, without cheating, the pre-med student would have gotten the higher grade. The answer is: Yes.  <br>以下是逐步分析：1. 约翰的分数：约翰获得了第 20 高的分数，这使他处于"A"等级范围的顶端。2. 医学预科生的分数：医学预科生获得了第 21 高的分数，这使她处于"B"等级范围的顶端。3. 对评分曲线的影响：如果约翰作弊并获得了更高的分数，他本可能以更高的分数进入"A"等级范围。这可能会使评分曲线上的分数整体下移。4. 学生的失败：如果约翰作弊并获得了更高的分数，评分曲线可能会下移，但这并非必然。5. 结论：医学预科生未能达到分数线与评分曲线有关。如果一些学生作弊，这改变了整体分布。很可能，如果没有作弊，医学预科生本可以获得更高的等级。答案是：是的。|
|136|Question: Alice and Zoe work for the same company. They work in different rooms and both of them sometimes need to access the central computer of the company. Unbeknownst to everybody, if two people are logged in to the central computer at the same time, some spam emails containing dangerous viruses are immediately deleted from the central computer. In order to make sure that one person is always available to answer incoming phone calls, the company issued the following official policy: Alice is the only one permitted to log in to the central computer in the mornings, whereas Zoe is the only one permitted to log in to the central computer in the afternoons. One day, violating the official policy, Zoe logs in to the central computer at 9 am. The same day, Alice also logs in at 9 am. Immediately, some spam emails containing dangerous viruses are deleted from the central computer. Did Alice cause some spam emails containing dangerous viruses to be removed from the central computer? Reply Yes or No based on the answer the majority of people would give. If you think people would be split roughly 50-50 between Yes and No then reply Ambiguous.  <br>问题：爱丽丝和佐伊在同一家公司工作。她们在不同的房间办公，两人有时都需要访问公司的中央计算机。无人知晓的是，如果两个人同时登录中央计算机，一些包含危险病毒的垃圾邮件会立即从中央计算机中删除。为了确保始终有人接听来电，公司发布了以下官方政策：上午只有爱丽丝被允许登录中央计算机，而下午只有佐伊被允许登录中央计算机。有一天，佐伊违反了官方政策，在上午 9 点登录了中央计算机。同一天，爱丽丝也在上午 9 点登录了中央计算机。随后，一些包含危险病毒的垃圾邮件立即从中央计算机中删除。爱丽丝是否导致了一些包含危险病毒的垃圾邮件从中央计算机中删除？根据大多数人会给出的答案回答是或否。如果你认为人们会大致在是和否之间各占一半，则回答模糊。|Yes  是|The question asks if Alice caused the deletion of spam emails. The scenario states that if Alice and Zoe are logged in simultaneously, the spam emails are deleted. Both Alice and Zoe logged in at the same time. Thus, Alice’s action, combined with Zoe’s, resulted in the deletion of the spam emails. The answer is: Yes"  <br>问题询问是否是爱丽丝导致了垃圾邮件的删除。情景说明，如果爱丽丝和佐伊同时登录，垃圾邮件就会被删除。爱丽丝和佐伊确实在同一时间登录了。因此，爱丽丝的行为与佐伊的行为共同导致了垃圾邮件的删除。答案是：是的。|

Table 6:Causal understanding: examples of causal judgment queries and correct or incorrect reasoning traces. Example ID corresponds to the index of the question in the causal understanding sub-benchmark.  
表 6：因果理解：因果判断查询及正确或错误推理轨迹的示例。示例 ID 对应因果理解子基准中问题的索引。

### A.4Causal Understanding  A.4 因果理解

In BBEH we replace the original causal judgement task in BBH with a set of questions that assess both (i) _causal judgement_ (142 queries) and (ii) the ability to determine _necessary and sufficient causes_ (58 queries). In this section we describe how these different sets of questions are obtained.  
在 BBEH 中，我们将 BBH 原有的因果判断任务替换为一组问题，用于评估（i）因果判断（142 个查询）和（ii）确定必要与充分原因的能力（58 个查询）。本节将描述这些不同问题集的获取方式。

#### Causal Judgement  因果判断

These queries are based on the 144 causal stories included in the MoCa benchmark (Nie et al., [2023](https://arxiv.org/html/2502.19187v2#bib.bib32)), which partially overlap with the sets of questions originally included in BBH. In MoCa, short stories obtained from cognitive science papers were given to 25 human annotators who had to judge whether, based on the given story, a certain person or event caused a certain outcome. The task was phrased as a binary task with Yes/No answers, and the ground truth label was assigned according to the label chosen by the majority of humans.  
这些查询基于 MoCa 基准测试中包含的 144 个因果故事（Nie 等人，2023 年），这些故事与 BBH 最初包含的问题集部分重叠。在 MoCa 中，从认知科学论文中获取的短篇故事被提供给 25 位人类标注者，他们必须根据给定的故事判断某个人或事件是否导致了某个结果。该任务被表述为二元任务，答案为是/否，而真实标签则根据大多数人类选择的标签来分配。

However, the stories included complex normative and logical factors, and for many of them there was a large degree of disagreement among the human annotators. In cases where the human raters strongly disagreed on the answer (defined as having a difference of at most 20% between the “Yes” and “No” answers among the annotators), questions were additionally tagged as “Ambiguous”. Based on this, we constructed the renewed task to have 3 possible labels: Yes, No and Ambiguous. The label ambiguous was assigned to the 46 questions originally tagged as “Ambiguous” in MoCa. For instance, the label for example 36 in Table [6](https://arxiv.org/html/2502.19187v2#A1.T6 "Table 6 ‣ A.3 Buggy Tables ‣ Appendix A Detailed Description of the Tasks and Task-Specific Insights from Experiments ‣ BIG-Bench Extra Hard") was changed from Yes to Ambiguous, as 15 human annotators replied Yes while 10 replied No. In this example we have that, on the one hand Billy was asked to be in the room at 9am and cannot be given the fault of entering the room and triggering the alarm. On the other hand, the alarm was set to be triggered if at least one person appeared in the room, thus both Billy and Suzy could be assigned the responsibility for the detector going off. Both explanation could be considered valid. For the remaining questions, the label was kept unchanged to Yes/No.  
然而，这些故事包含了复杂的规范性和逻辑性因素，其中许多故事在人类标注者之间存在较大程度的分歧。在人类评分者对答案存在强烈分歧的情况下（定义为标注者中“是”和“否”答案之间的差异不超过 20%），问题被额外标记为“模糊”。基于此，我们构建了更新后的任务，包含三种可能的标签：是、否和模糊。模糊标签被分配给最初在 MoCa 中被标记为“模糊”的 46 个问题。例如，表 6 中示例 36 的标签从“是”改为“模糊”，因为 15 名人类标注者回答“是”，而 10 名回答“否”。在这个例子中，一方面，比利被要求在上午 9 点进入房间，不能因进入房间并触发警报而受到指责。另一方面，警报被设置为如果至少一个人出现在房间内就会触发，因此比利和苏西都可能被认定为探测器响起的责任人。两种解释都可以被认为是有效的。对于其余的问题，标签保持不变，仍为“是”或“否”。

With the above re-definition of ground truth labels, models were then asked to correctly identify the way humans, as a group, would answer the question, thus testing alignment with human causal intuitions. To reflect this, we added the following instructions to each query:  
在重新定义真实标签的基础上，我们要求模型正确识别人类作为一个群体会如何回答问题，从而测试其与人类因果直觉的一致性。为体现这一点，我们在每个查询中加入了以下说明：

Finally, to ensure consistency in terms of number of queries included for the other tasks, we removed 2 stories included in the original set (these correspond to question 17 and 19 at [https://moca-llm.github.io/causal_stories/1/](https://moca-llm.github.io/causal_stories/1/)). The final set includes 45 Ambiguous questions and 48 and 49 questions with Yes and No labels respectively.  
最后，为确保其他任务所含查询数量的一致性，我们移除了原始集合中的 2 个故事（对应 https://moca-llm.github.io/causal_stories/1/中的问题 17 和 19）。最终集合包含 45 个模糊问题，以及分别带有“是”和“否”标签的 48 个和 49 个问题。

#### Necessary and Sufficient Causes  
必要与充分原因

We complemented the causal judgement stories with 58 examples testing reasoning about necessary and sufficient causes given a description of a set of events (example scenario). These examples were obtained by modifying those in Kıcıman et al. ([2023](https://arxiv.org/html/2502.19187v2#bib.bib23)) to correct ambiguities and incorrect outputs.  
我们补充了因果判断故事，增加了 58 个测试案例，这些案例基于对一组事件（示例场景）的描述来检验关于必要与充分原因的推理能力。这些案例是通过修改 Kıcıman 等人（2023 年）的研究成果而获得的，旨在纠正其中的模糊之处和错误输出。

The first 30 examples in Kıcıman et al. ([2023](https://arxiv.org/html/2502.19187v2#bib.bib23)) were constructed from 15 scenarios introduced in different studies over the years to critique actual causality (Halpern, [2016](https://arxiv.org/html/2502.19187v2#bib.bib13)) definitions from the literature (Kueffner, [2021](https://arxiv.org/html/2502.19187v2#bib.bib25)). Each scenario is associated with a question about necessary cause and a question about sufficient cause, specifically “Is {Actor} a necessary cause of {Event}?” and “Is {Actor} a sufficient cause of {Event}?”. To test LLM memorization issues, Kıcıman et al. ([2023](https://arxiv.org/html/2502.19187v2#bib.bib23)) constructed 28 additional examples from 14 new scenarios obtained by adapting the original ones to a chemistry lab setting involving reagents, mixtures and crystals.  
Kıcıman 等人（2023 年）研究中的前 30 个案例，源自多年来不同研究中引入的 15 个场景，这些场景旨在批判文献中关于实际因果关系的定义（Halpern，2016 年；Kueffner，2021 年）。每个场景都关联着一个关于必要原因的问题和一个关于充分原因的问题，具体为“{行动者}是{事件}的必要原因吗？”和“{行动者}是{事件}的充分原因吗？”。为了测试 LLM 的记忆问题，Kıcıman 等人（2023 年）通过将原始场景改编为涉及试剂、混合物和晶体的化学实验室环境，从 14 个新场景中构建了另外 28 个案例。

Three experts of causal reasoning analysed each example and suggested minimal changes to resolve ambiguities, typos, and incorrect outputs. The main ambiguities that were identified relates to the use of {Actor}, which was substituted with the associated action. Each example was discussed to reach an agreement on the changes, this resulted in changing the outputs of six examples (see Table [7](https://arxiv.org/html/2502.19187v2#A1.T7 "Table 7 ‣ Model Outputs Analysis ‣ A.4 Causal Understanding ‣ Appendix A Detailed Description of the Tasks and Task-Specific Insights from Experiments ‣ BIG-Bench Extra Hard")).  
三位因果推理专家分析了每个示例，并提出最小化修改建议以消除歧义、修正拼写错误和纠正错误输出。识别出的主要歧义与{Actor}的使用有关，该占位符已被替换为相关动作。通过讨论每个示例以就修改达成共识，最终修改了六个示例的输出（见表 7）。

#### Model Outputs Analysis  模型输出分析

Analysing the performance that Gemini 2.0 Flash achieves on the causal understanding task reveals that this model answers correctly to 45% of the causal judgment queries (random performance is 33%) and 71% of the queries about necessary and sufficient causes (random performance is 50%).  
分析 Gemini 2.0 Flash 在因果理解任务上的表现显示，该模型对 45%的因果判断查询给出了正确答案（随机正确率为 33%），并对 71%关于必要和充分原因的查询给出了正确答案（随机正确率为 50%）。

Focusing on the causal judgment queries, most of the errors are in questions for which the ground truth label is Ambiguous (44 mistakes out of 45 examples) or No (24 mistakes out of 49 examples), with only 10 mistakes out of 48 examples for the Yes label. This reveals the difficulty the model has in determining an absence of causal relationships, and in dealing with ambiguities and the existence of different possible answers. This behaviour has been previously observed across other causal reasoning benchmarks (see e.g. Romanou et al. ([2023](https://arxiv.org/html/2502.19187v2#bib.bib36))) where models have been found to infer stronger causal relationships than those that humans perceive. Another interesting failure mode is that the model sometimes exhibits a lack of understanding of the _normative_ aspect of causal judgements as made by humans: humans tend to ascribe causality more easily when the causal factor is unusual in a statistical sense, or when it violates an established rule or behavioral norm (Halpern, [2008](https://arxiv.org/html/2502.19187v2#bib.bib12); Phillips et al., [2015](https://arxiv.org/html/2502.19187v2#bib.bib35); Kominsky et al., [2015](https://arxiv.org/html/2502.19187v2#bib.bib24); Halpern and Hitchcock, [2015](https://arxiv.org/html/2502.19187v2#bib.bib14); Icard et al., [2017](https://arxiv.org/html/2502.19187v2#bib.bib18)). For instance, in example 136 of Table [6](https://arxiv.org/html/2502.19187v2#A1.T6 "Table 6 ‣ A.3 Buggy Tables ‣ Appendix A Detailed Description of the Tasks and Task-Specific Insights from Experiments ‣ BIG-Bench Extra Hard"), the event can only occur if both Alice and Zoe log on simultaneously to a computer – which is indeed what happened. However, Alice was allowed to log on while Zoe violated an established rule when she logged in. In such situations, humans tend to say that Alice did not cause the event, while Zoe did. The model fails to capture this nuance and instead it applies straightforward causal reasoning and concludes that Alice is a cause.  
在因果判断查询方面，大多数错误出现在真实标签为“模糊”（45 个示例中有 44 个错误）或“否”（49 个示例中有 24 个错误）的问题上，而“是”标签的 48 个示例中仅有 10 个错误。这表明模型在确定因果关系缺失、处理模糊性以及应对多种可能答案方面存在困难。这种行为在其他因果推理基准测试中已有先例（例如 Romanou 等人（2023 年）的研究），其中发现模型推断出的因果关系比人类感知到的更为强烈。 另一个有趣的失败模式是，模型有时未能理解人类进行因果判断时所依据的规范性层面：当因果因素在统计意义上非同寻常，或违反既定规则或行为规范时，人类往往更容易归因于因果关系（Halpern, 2008; Phillips et al., 2015; Kominsky et al., 2015; Halpern and Hitchcock, 2015; Icard et al., 2017）。例如，在表 6 的示例 136 中，只有当爱丽丝和佐伊同时登录一台计算机时，事件才会发生——而这正是实际发生的情况。然而，爱丽丝被允许登录，而佐伊登录时违反了一项既定规则。在这种情况下，人类倾向于认为爱丽丝不是事件的原因，而佐伊才是。模型未能捕捉到这种细微差别，而是直接应用因果推理，得出爱丽丝是原因的结论。

Looking at the reasoning traces for Gemini 2.0 Flash responses to questions on sufficient and necessary causes reveals that, while the model achieves very close performances in terms of precision and recall, it fails on identifying sufficient causes (11 errors out of 28 examples) more often than identifying necessary causes (6 errors out of 30 examples). Interestingly, the model correctly recalls the definition of necessary and sufficient causes in most of the responses and uses counterfactual reasoning to consider alternative scenarios. Despite this, the model often fails at interpreting some of the causal links described in the scenarios (in example 155 of Table [7](https://arxiv.org/html/2502.19187v2#A1.T7 "Table 7 ‣ Model Outputs Analysis ‣ A.4 Causal Understanding ‣ Appendix A Detailed Description of the Tasks and Task-Specific Insights from Experiments ‣ BIG-Bench Extra Hard") the model interprets the input as implying that “flowers would likely die in hot weather whether the neighbor waters or not”) or draws incorrect conclusions despite correct reasoning traces.  
通过分析 Gemini 2.0 Flash 对充分与必要原因问题的推理轨迹可以发现，尽管该模型在精确率和召回率方面表现极为接近，但在识别充分原因时（28 个示例中出现 11 次错误）比识别必要原因时（30 个示例中出现 6 次错误）更容易出错。值得注意的是，该模型在大多数回答中能正确复述必要与充分原因的定义，并运用反事实推理来考量替代情境。尽管如此，模型仍时常无法准确解读情境中描述的某些因果联系（如表 7 示例 155 中，模型将输入内容误解为“无论邻居是否浇水，鲜花在炎热天气中都可能死亡”），或在推理轨迹正确的情况下仍得出错误结论。

|   |   |   |   |   |
|---|---|---|---|---|
|Example ID  示例 ID|Original Input  原始输入|Original Output  原始输出|Modified Input  修改后的输入|Modified Output  修改后的输出|
|149|Two two-state switches are wired to an electrode. The switches are controlled by A and B respectively, and the electrode is attached to C. A has the first option to flip her switch. B has the second option to flip her switch. The electrode is activated and shocks C if both switches are in the same position. B wants to shock C, and so flips her switch iff A does. C gets an electric shock. Is A’s action to flip the switch a necessary cause for C getting shocked?  <br>两个双态开关连接到一个电极上。开关分别由 A 和 B 控制，电极连接到 C 身上。A 拥有优先翻转开关的权利。B 拥有第二个翻转开关的权利。如果两个开关处于相同位置，电极就会激活并电击 C。B 想要电击 C，因此当且仅当 A 翻转开关时，B 才会翻转开关。C 遭到了电击。A 翻转开关的行为是否是 C 遭到电击的必要原因？|No  不|Two two-state switches are wired to an electrode. The switches are controlled by A and B respectively, and the electrode is attached to C. A has the first option to flip her switch. B has the second option to flip her switch. The electrode is activated and shocks C if both switches are flipped. B wants to shock C, and so flips her switch if and only if A does. C gets an electric shock. Is A’s action to flip the switch a necessary cause for C getting shocked?  <br>两个双态开关连接到一个电极上。开关分别由 A 和 B 控制，电极连接到 C 身上。A 拥有优先翻转开关的权利。B 拥有第二个翻转开关的权利。如果两个开关都被翻转，电极就会激活并电击 C。B 想要电击 C，因此当且仅当 A 翻转开关时，B 才会翻转开关。C 遭到了电击。A 翻转开关的行为是否是 C 遭到电击的必要原因？|Yes  是|
|154|There are a left and a right window. Alice and Bob both order Carol to fire at the left window. Carol fires at the left window, shattering it. Commands from Alice always trump commands form Bob (e.g. if Bob would have ordered to fire at right window, Carol would still have fired at the left one.). Without a command Carol would not have fired at all. Is Alice a necessary cause for window shattering?  <br>有一扇左窗和一扇右窗。爱丽丝和鲍勃都命令卡罗尔向左窗射击。卡罗尔向左窗射击，将其击碎。爱丽丝的命令总是优先于鲍勃的命令（例如，如果鲍勃命令向右窗射击，卡罗尔仍然会向左窗射击）。没有命令的话，卡罗尔根本不会射击。爱丽丝是窗户破碎的必要原因吗？|Yes  是|There are a left and a right window. Alice and Bob both order Carol to fire at the left window. Carol fires at the left window, shattering it. Commands from Alice always trump commands from Bob (e.g. if Bob would have ordered to fire at the right window, Carol would still have fired at the left one). Without a command Carol would not have fired at all. Is Alice ordering Carol to fire a necessary cause for the window shattering?  <br>有一扇左窗和一扇右窗。爱丽丝和鲍勃都命令卡罗尔向左窗射击。卡罗尔向左窗射击，将其击碎。爱丽丝的命令总是优先于鲍勃的命令（例如，如果鲍勃命令向右窗射击，卡罗尔仍然会向左窗射击）。没有命令的话，卡罗尔根本不会射击。爱丽丝命令卡罗尔射击是窗户破碎的必要原因吗？|No  不|
|155|If there is hot weather, flowers will die. Watering prevents the flowers to die in hot weather. The neighbor does not water the flowers in her yard. The flowers die. Is neighbor’s inaction a necessary cause for flowers’ death?  <br>如果天气炎热，花朵就会死亡。浇水可以防止花朵在炎热天气中死亡。邻居没有给院子里的花浇水。花朵死亡了。邻居的不作为是花朵死亡的必要原因吗？|No  不|If there is hot weather, flowers will die. Watering prevents the flowers from dying in hot weather. The neighbor does not water the flowers in her yard, the weather is hot and the flowers die. Is the neighbor’s inaction a necessary cause for the flowers’ death?  <br>如果天气炎热，花朵就会死亡。浇水可以防止花朵在炎热天气中死亡。邻居没有给院子里的花浇水，天气炎热，花朵死亡了。邻居的不作为是花朵死亡的必要原因吗？|Yes  是|
|170|If there is hot weather, flowers will die. Watering prevents the flowers to die in hot weather. The neighbor does not water the flowers in her yard. The flowers die. Is neighbor’s inaction a sufficient cause for flowers’ death?  <br>如果天气炎热，花朵就会死亡。浇水可以防止花朵在炎热天气中死亡。邻居没有给院子里的花浇水。花朵死亡了。邻居的不作为是花朵死亡的充分原因吗？|Yes  是|If there is hot weather, flowers will die. Watering prevents the flowers from dying in hot weather. The neighbor does not water the flowers in her yard, the weather is hot and the flowers die. Is the neighbor’s inaction a sufficient cause for the flowers’ death?  <br>如果天气炎热，花朵就会死亡。浇水可以防止花朵在炎热天气中死亡。邻居没有给院子里的花浇水，天气炎热，花朵死亡了。邻居的不作为是花朵死亡的充分原因吗？|No  不|
|177|Reagent X is added to a beaker containing a crystal. If Reagent X touches the crystal, the crystal dissolves. If Reagent X does not touch the crystal, Sam adds Reagent Y which leads to the crystal dissolving. Is Reagent X a necessary cause for crystal dissolving?  <br>将试剂 X 加入装有晶体的烧杯中。如果试剂 X 接触到晶体，晶体会溶解。如果试剂 X 未接触到晶体，Sam 会加入试剂 Y，这也会导致晶体溶解。试剂 X 是晶体溶解的必要原因吗？|No  不|Reagent X is added to a beaker containing a crystal. If Reagent X touches the crystal, the crystal dissolves. If, when added, Reagent X does not touch the crystal, Sam adds Reagent Y, which leads the crystal to dissolve. Is adding Reagent X to the beaker a necessary cause for the crystal to dissolve?  <br>将试剂 X 加入装有晶体的烧杯中。如果试剂 X 接触到晶体，晶体会溶解。如果加入时试剂 X 未接触晶体，萨姆会添加试剂 Y，这也会导致晶体溶解。那么，加入试剂 X 是晶体溶解的必要原因吗？|Yes  是|
|183|There is a test tube on the left and a test tube on the right. Sam and Riya both order Frank to break the left test tube. Carol throws the left test tube, breaking it. Commands from Sam always trump commands form Riya (e.g. if Riya would have ordered to break the right test tube, Frank would still have thrown the left one.). Without a command Frank would not have acted at all. Is Sam a necessary cause for test tube breaking?  <br>左边有一个试管，右边也有一个试管。萨姆和里亚都命令弗兰克打破左边的试管。卡罗尔扔出左边的试管，将其打破。萨姆的命令总是优先于里亚的命令（例如，如果里亚命令打破右边的试管，弗兰克仍会扔出左边的试管）。如果没有命令，弗兰克根本不会采取行动。那么，萨姆是试管破裂的必要原因吗？|Yes  是|There is a test tube on the left and a test tube on the right. Sam and Riya both order Frank to break the left test tube. Frank throws the left test tube, breaking it. Commands from Sam always trump commands from Riya (e.g. if Riya would have ordered to break the right test tube, Frank would still have thrown the left one). Without a command Frank would not have acted at all. Is Sam’s order a necessary cause for the test tube to break?  <br>左边有一个试管，右边也有一个试管。萨姆和里亚都命令弗兰克打破左边的试管。弗兰克扔出左边的试管，将其打破。萨姆的命令总是优先于里亚的命令（例如，如果里亚命令打破右边的试管，弗兰克仍会扔出左边的试管）。如果没有命令，弗兰克根本不会采取行动。那么，萨姆的命令是试管破裂的必要原因吗？|No  不|

Table 7:Causal understanding: queries for which the output was changed with respect to the original dataset in Kıcıman et al. ([2023](https://arxiv.org/html/2502.19187v2#bib.bib23)). Example ID corresponds to the index of the question in the causal understanding sub-benchmark.  
表 7：因果理解：与 Kıcıman 等人（2023）原始数据集相比输出发生变化的查询。示例 ID 对应因果理解子基准中问题的索引。

### A.5Disambiguation QA  A.5 消歧问答

This task introduces a more challenging adaptation of the original DisambiguationQA task in BBH. The objective is to accurately determine the referents of ambiguous pronouns in complex sentences, or to explicitly identify instances of unresolvable ambiguity by responding ’ambiguous’. To enhance the task’s difficulty and complexity, we constructed a dataset of 120 novel examples that are longer than those in BBH, require more referent disambiguation, and each question contains more options so the random chance performance is lower. These examples were constructed either by creating entirely new sentences or combining existing BBH instances. Ten annotators (all of them the authors of the paper) were tasked with creating these examples, each comprising a potentially ambiguous sentence, a single correct resolution statement, and several distractor options for a multiple-choice format. To ensure data quality, each example underwent a two-stage verification process. First, a separate annotator independently evaluated the correctness of the resolution. Discrepancies were then resolved through a third-party adjudicator or collaborative refinement by all three annotators. In cases where consensus could not be reached, the annotators jointly revised the example to achieve clarity and accuracy. This rigorous process resulted in 25 examples requiring modification. An example of an ambiguous sentence is provided below.  
本任务在 BBH 原有消歧问答任务基础上，提出了更具挑战性的改编版本。其核心目标是精准识别复杂句子中歧义代词的指代对象，或通过回答"ambiguous"明确标注无法消解的歧义实例。为提升任务的难度与复杂性，我们构建了包含 120 个新颖样例的数据集：这些例句较 BBH 原句更长、需要更多指代消解步骤，且每个问题包含更多选项以降低随机猜测准确率。这些样例通过创造全新句子或组合现有 BBH 实例构建而成。十位标注者（均为论文作者）负责创建这些样例，每个样例包含一个可能存在歧义的句子、一个正确消解陈述以及若干用于多选题形式的干扰选项。为确保数据质量，每个样例均经过两阶段验证流程：首先由独立标注者评估消解结果的正确性，若出现分歧则通过第三方仲裁或三位标注者协同修正达成共识。 在无法达成共识的情况下，标注员共同修改示例以确保清晰度和准确性。这一严格流程最终导致 25 个示例需要修改。以下是一个模糊句子的示例。

### A.6Dyck Languages  A.6 迪克语言

This task comes from the BIG-Bench Mistake dataset (Tyen et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib53)). It involves finding the first mistake in an existing chain-of-thought sequence, used to answer a Dyck Languages question in the original BBH dataset. In each example, the target answer is either the number where the first mistake occurred, or that there are no mistakes in the CoT sequence. These CoT sequences are generated by prompting PaLM 2 Unicorn (Anil et al., [2023](https://arxiv.org/html/2502.19187v2#bib.bib2)) on the original BBH dataset at temperature = 0. The prompts can be found at [https://github.com/suzgunmirac/BIG-Bench-Hard/blob/main/cot-prompts/dyck_languages.txt](https://github.com/suzgunmirac/BIG-Bench-Hard/blob/main/cot-prompts/dyck_languages.txt). The newline is used as a stop token so that each intermediate step can be prepended with ‘Thought 1: ’, ‘Thought 2: ’, etc. Further information on the prompting and generation process can be found in Tyen et al. ([2024](https://arxiv.org/html/2502.19187v2#bib.bib53)).  
本任务源自 BIG-Bench 错误数据集（Tyen 等人，2024 年）。它涉及在现有思维链序列中找出第一个错误，该序列原本用于回答原始 BBH 数据集中的戴克语言问题。每个示例中，目标答案要么是第一个错误出现的位置编号，要么是思维链序列中不存在错误。这些思维链序列是通过在原始 BBH 数据集上以温度=0 提示 PaLM 2 Unicorn 模型（Anil 等人，2023 年）生成的。提示词可在 https://github.com/suzgunmirac/BIG-Bench-Hard/blob/main/cot-prompts/dyck_languages.txt 找到。换行符被用作停止标记，因此每个中间步骤都可以加上“思考 1：”、“思考 2：”等前缀。关于提示和生成过程的更多信息详见 Tyen 等人（2024 年）的研究。

In the cases where there is an error in the trace and the model makes a mistake in identifying the first error, the mistake can occur due to two different reasons: 1- mis-classifying a correct reasoning step as erroneous before any error has occurred, and 2- missing the first error and identifying some later erroneous step. We looked into the breakdown of what percentage of the errors belong to each category when there is an error to be found and the model also identifies one of the steps as erroneous.  
在追踪过程中出现错误且模型在识别首个错误时出错的情况下，错误可能由两种不同原因导致：1- 在尚未发生任何错误时，将正确的推理步骤误判为错误；2- 遗漏首个错误，而识别出后续的某个错误步骤。我们深入分析了当存在可发现的错误且模型也将某个步骤识别为错误时，各类错误所占的百分比分布情况。

We find that the majority of the errors belong to the second category. Specifically, for o3-mini (high) 98.7% of the errors belong to the second class, for Gemini 2.0 Flash all the errors belong to the second class, for Gemini 2.0 Flash-Lite 94.9% and for GPT4o 96.8% of the errors belong to the second class. This highlights a failure mode for the frontier models in that they can identify the correct reasoning steps, but fail to identify the ones that have errors.  
我们发现，绝大多数错误属于第二类。具体而言，对于 o3-mini（高精度版），98.7%的错误属于第二类；对于 Gemini 2.0 Flash，所有错误均属于第二类；对于 Gemini 2.0 Flash-Lite，94.9%的错误属于第二类；对于 GPT4o，96.8%的错误属于第二类。这凸显了前沿模型的一种失效模式：它们能够识别正确的推理步骤，却无法识别其中存在错误的步骤。

### A.7Geometric Shapes  A.7 几何形状

SVG is a language for drawing shapes. We use two basic commands: 1- M⁢(x,y) corresponding to moving to the (x,y) coordinate, and 2- L⁢(x,y) corresponding to drawing a line from the current location to (x,y). We use the shape outlines from GeomVerse (Kazemi et al., [2023a](https://arxiv.org/html/2502.19187v2#bib.bib19)), a dataset of geometry questions involving multiple shapes that share some elements, which are specified as TikZ commands and convert them to SVG. We then ask the model to identify what shapes will be drawn if we visualize the SVG.  
SVG 是一种用于绘制图形的语言。我们使用两个基本命令：1- M⁢(x,y) 对应移动到 (x,y) 坐标，2- L⁢(x,y) 对应从当前位置到 (x,y) 绘制一条直线。我们采用 GeomVerse（Kazemi 等人，2023a）中的图形轮廓——这是一个涉及多个共享某些元素的几何问题数据集，这些元素以 TikZ 命令形式指定，并将其转换为 SVG。随后，我们要求模型识别：若将 SVG 可视化，将会绘制出哪些图形。

We consider two extra axes for difficulty: 1- we randomly break some lines segments into multiple colinear line segments, and 2- we add some extra lines such that they intersect at some points and those intersections form some shapes (in other cases, shapes are created using the full line segments and not at their intersection points). We then create four subsets for the task corresponding to the cross product of few vs many line breaks and intersect vs no intersect.  
我们为难度设置了两个额外维度：1- 随机将某些线段拆分为多个共线线段，2- 添加额外线段使其在某些点相交，这些交点构成特定图形（其他情况下，图形由完整线段直接构成而非通过交点形成）。基于此，我们为任务创建了四个子集，分别对应"少量线段拆分 vs 大量线段拆分"与"存在交点 vs 无交点"的交叉组合。

For o3-mini (high), which is the best performing model on this task, we observe that the accuracy for the _few breaks_ subset is 58% while the accuracy for the _many breaks_ subset is 47%; we also observe that the accuracy for the _no intersect_ subset is 72% while for the _intersect_ subset is 33%. This shows that both axes are adding to the difficulty of the task.  
对于在此任务中表现最佳的 o3-mini（高）模型，我们观察到其"少量中断"子集的准确率为 58%，而"大量中断"子集的准确率为 47%；同时"无交集"子集的准确率为 72%，而"有交集"子集的准确率为 33%。这表明两个维度都在增加任务的难度。

### A.8Hyperbaton  A.8 倒装法

In English, a prescribed order governs the sequence of multiple adjectives preceding a noun. This order, generally, is: opinion → size → age → shape → color → origin → material → purpose. The BBH suite includes Hyperbaton, an adjective ordering task designed to evaluate a model’s linguistic knowledge—specifically, its understanding of adjective categories and adherence to the correct adjective ordering in English. In this task, models must choose the sentence with the correct adjective sequence from a pair of English sentences. Current general-purpose models excel at this task, reaching nearly 95% accuracy (see Table [10](https://arxiv.org/html/2502.19187v2#A2.T10 "Table 10 ‣ Appendix B BBEH vs BBH Performance ‣ BIG-Bench Extra Hard") for Gemini 2.0 Flash performance on Hyperbaton task from BBH).  
在英语中，多个形容词修饰名词时需遵循特定顺序。这一顺序通常为：观点 → 尺寸 → 年龄 → 形状 → 颜色 → 起源 → 材质 → 用途。BBH 测试集包含"Hyperbaton"任务，即形容词排序测试，旨在评估模型的语言学知识——特别是对形容词类别的理解及英语形容词正确排序规则的掌握。该任务要求模型从一对英语句子中选出形容词顺序正确的句子。当前通用模型在此任务上表现优异，准确率接近 95%（详见 Gemini 2.0 Flash 在 BBH 的 Hyperbaton 任务表现，表 10）。

We replace Hyperbaton with a novel task that assesses inductive reasoning in addition to linguistic knowledge. This new task involves inducing the correct adjective order in a new variant of English, given a set of example sentences. Specifically, for each test sample, we create a unique English variant by randomly shuffling the standard adjective order and generating 50-250 sentences. Each sentence contains 1 to 3 adjectives preceding a noun. Models must then infer the correct adjective order for this variant and identify all correct sentences from 10 provided options. A “None of the above” option is included as a distractor. We observe that this variant already poses a challenge for latest general-purpose models. To further increase the difficulty, we ensure that the provided sentences only reveal partial adjective orderings, such as opinion, size, shape, color, purpose, age, and material, origin, without specifying the relative order of all categories (e.g., whether material precedes or follows age, or whether origin precedes or follows opinion). This requires models to reason with partial information and avoid relying on prior knowledge.  
我们用一项新任务替代了 Hyperbaton，该任务不仅评估语言知识，还评估归纳推理能力。这项新任务要求根据一组例句，推断出一种新英语变体中正确的形容词顺序。具体而言，针对每个测试样本，我们通过随机打乱标准形容词顺序并生成 50 至 250 个句子，创建一种独特的英语变体。每个句子包含 1 到 3 个位于名词前的形容词。模型必须推断出该变体中正确的形容词顺序，并从提供的 10 个选项中识别所有正确的句子。选项包含一个“以上都不是”作为干扰项。我们观察到，这种变体已经对最新的通用模型构成了挑战。为了进一步增加难度，我们确保提供的句子仅揭示部分形容词排序类别，如观点、大小、形状、颜色、用途、年龄、材质和来源，而不指定所有类别的相对顺序（例如，材质是在年龄之前还是之后，或者来源是在观点之前还是之后）。这要求模型能够基于部分信息进行推理，避免依赖先验知识。

We observe an interesting failure mode in this task: some models correctly induce partial adjective orderings but rely on prior knowledge of standard English order when selecting answers. Consider the example below.  
我们在这项任务中观察到一个有趣的失败模式：某些模型能够正确推导出部分形容词排序规则，但在选择答案时却依赖于对标准英语语序的先验知识。请看以下示例。

o3-mini (high) provides the following response:  
o3-mini（高）提供以下回应：

Although the model correctly infers the partial adjective orderings: (i) size → color → purpose → shape → opinion → origin, and (ii) material → age, it incorrectly assumes that material follows origin. This assumption likely stems from prior knowledge of standard English ordering (opinion → size → age → shape → color → origin → material → purpose). While the model correctly identifies option D, the only correct answer, its incorrect assumption leads it to also select options A, C, E, H, and I.  
尽管模型正确推断出部分形容词顺序：(i) 尺寸→颜色→用途→形状→观点→来源，以及(ii) 材质→年龄，但它错误地假设材质位于来源之后。这一假设很可能源于对标准英语顺序（观点→尺寸→年龄→形状→颜色→来源→材质→用途）的先验知识。虽然模型正确识别出唯一正确答案选项 D，但其错误假设导致它同时选择了选项 A、C、E、H 和 I。

### A.9Linguini  A.9 意大利细面

This task comes from Sánchez et al. ([2024](https://arxiv.org/html/2502.19187v2#bib.bib38)) and its problems are extracted from the International Linguistic Olympiad (IOL). According to the original work that introduced this dataset, the problems are _"linguistic problems which require meta-linguistic awareness and deductive reasoning capabilities to be solved instead of pre-existing language proficiency"_.  
本任务源自 Sánchez 等人（2024）的研究，其问题选自国际语言学奥林匹克竞赛（IOL）。根据引入该数据集的原始文献描述，这些问题属于"需要借助元语言意识和演绎推理能力来解决的语言学问题，而非依赖预先掌握的语言熟练度"。

We created a subset of the Linguini problems by sampling from four categories of the Linguini problems, namely _translation_, _fill blanks_, _num to text_ and _text to num_. The original dataset contains questions that require multiple answers. For example, the _fill blanks_ questions have multiple blanks that need to be filled. We create questions that have a single answer by randomly selecting one of those blanks and only asking the model to fill that one.  
我们通过从 Linguini 问题的四个类别（即翻译、填空、数字转文字和文字转数字）中抽样，创建了 Linguini 问题的子集。原始数据集包含需要多个答案的问题，例如填空题存在多个待填空白。我们通过随机选取其中一个空白并仅要求模型填写该处答案，构建了仅需单一答案的问题形式。

### A.10Movie Recommendation  A.10 电影推荐

The original Movie Recommendation task in BBH has been created as follows. For each question, a set of eight movies from MovieLens have been selected such that a rather large number of people have all liked five of them and disliked three of them. Then, a question has been generated by giving four of the five liked movies and asking models to recommend one of the remaining four movies, where the correct answer is the one left out of the 5 liked movies.  
BBH 中的原始电影推荐任务创建方式如下：针对每个问题，从 MovieLens 中选取八部电影，确保有相当多的人群同时喜欢其中的五部而不喜欢另外三部。随后，通过展示五部受喜爱电影中的四部，并要求模型从剩余四部电影中推荐一部来生成问题，其中正确答案即为五部受喜爱电影中未被展示的那一部。

We updated this task as follows. We create multiple sets of movies where one of them contains the five liked movies and the other ones contain some of the liked movies and some of the disliked movies. Then, we ask the model to select the set that contains movies that are more likely to all be liked by a large group of people. In the new variant we created, instead of recommending a single movie given four movies, models have to examine each set separately and predict their overall likability, and then decide the option that is more likely to have a likability score with our specific definition of likeability.  
我们对任务进行了如下更新。我们创建了多组电影，其中一组包含五部受喜爱的电影，其他组则包含部分受喜爱和部分不受喜爱的电影。然后，我们要求模型选择那组更可能被广大人群全部喜爱的电影。在我们创建的新变体中，模型不再是根据四部电影推荐单部电影，而是需要分别检查每组电影，预测它们的整体受欢迎程度，然后根据我们对受欢迎程度的特定定义，决定哪一选项更可能获得较高的受欢迎度评分。

### A.11Multi-step Arithmetic  
A.11 多步算术

This task introduces new arithmetic operators. An example of such an operator is as follows:  
本任务引入了新的算术运算符。此类运算符的一个示例如下：

Some of the operations can be defined based on the other new operations. For example we may have:  
部分操作可以根据其他新操作来定义。例如，我们可能有：

We also define a form of composing multiple operations as follows: a <op1><op2> b denotes (a op1 b) op2 b; for example, 4 +* -5 means (4 +  5) * -5 and 4 *++ 5 means (4 * 5) ++ 5.  
我们还定义了一种组合多个运算的形式如下：a <op1><op2> b 表示 (a op1 b) op2 b；例如，4 +* -5 表示 (4 + 5) * -5，而 4 *++ 5 表示 (4 * 5) ++ 5。

Then we sample random arithmetic expressions involving the above operations. An example expression is: (1 @*+ 4) <>+[] (-4 *<>* -1) (although our expressions are longer), with @, <>, and [] being new operations. The job of the model is to compute the value of the expression. Being able to compute these expressions requires expanding the expressions and making a long list of computations correctly.  
接着，我们从涉及上述运算的随机算术表达式中进行抽样。一个示例表达式为：(1 @*+ 4) <>+[] (-4 *<>* -1)（尽管我们的表达式更长），其中@、<>和[]是新的运算。模型的任务是计算表达式的值。能够计算这些表达式需要展开表达式并正确执行一系列冗长的计算。

Upon looking at the outputs generated by the models, we find a common failure mode is that when multiple operations are composed, models sometimes forget to apply all of them despite understanding how the operator composition works. For instance, in one of our examples, while o3-mini correctly explains how the operator composition works in its reasoning trace, it still computes (1∗><−−6) as (1∗−6)><−6 and forgets the final subtraction operator in the composed operator ∗⁣>⁣<⁣−.  
在查看模型生成的输出时，我们发现一个常见的失败模式是：当多个操作组合在一起时，模型有时会忘记应用所有操作，尽管它们理解操作符组合的工作原理。例如，在我们的一个示例中，虽然 o3-mini 在其推理轨迹中正确解释了操作符组合的工作原理，但它仍然将 (1∗><−−6) 计算为 (1∗−6)><−6 ，并忘记了组合操作符 ∗⁣>⁣<⁣− 中的最终减法操作符。

### A.12NYCC

This task builds on the existing benchmarks for the New Yorker Caption Contest (NYCC) dataset Hessel et al. ([2022](https://arxiv.org/html/2502.19187v2#bib.bib16)); Zhang et al. ([2024](https://arxiv.org/html/2502.19187v2#bib.bib66)). The NYCC caption dataset consists of a) several hundred contests, each of which is a cartoon published in the New Yorker magazine and several thousand submitted humorous captions, b) crowdsourced ratings for each caption. The ratings are on a scale of “Unfunny”, “Somewhat Funny”, and “Funny”, and each caption has anywhere from a few dozen to a few thousand ratings. Past works have focused on pairwise comparison tasks, where two captions and a textual description of the cartoon are presented to the model, and the model has to pick the funnier of the two. As discussed in these works, the model tends to be fairly successful at these tasks, with GPT-4 Turbo getting to ≈ 70% accuracy.  
本任务基于《纽约客》标题竞赛（NYCC）数据集现有基准进行扩展（Hessel 等人，2022；Zhang 等人，2024）。NYCC 标题数据集包含：a) 数百个竞赛单元，每个单元对应《纽约客》杂志刊登的一幅漫画及数千条投稿的幽默标题；b) 每条标题的众包评分。评分采用“不好笑”、“有点好笑”和“好笑”三级量表，每条标题通常获得数十至数千次评分。既往研究主要聚焦于成对比较任务：向模型展示两条标题及漫画的文字描述，要求模型选出两者中更有趣的一条。相关研究指出，模型在此类任务中表现相当成功，例如 GPT-4 Turbo 的准确率可达约 70%。

To make the task significantly more difficult, for each contest we sample one query from the top ten rated, and then take captions ranked 1000-1009 and ask the model to choose the funniest. We use the “Canny” textual descriptions of the cartoons generated by GPT-4o that are provided in Zhang et al. ([2024](https://arxiv.org/html/2502.19187v2#bib.bib66)). An example query is below.  
为了使任务难度显著增加，我们在每场比赛中从前十名中抽取一个查询，然后选取排名 1000 至 1009 的标题，要求模型从中选出最有趣的一个。我们使用了 Zhang 等人（2024）提供的由 GPT-4o 生成的卡通图像“Canny”文本描述。以下是一个示例查询。

In the above the correct caption is caption number 9. Adding multiple possible options makes the task significantly more challenging compared to the pairwise task.  
在上述内容中，正确的标题是标题编号 9。与成对任务相比，添加多个可能的选项使得任务难度显著增加。

### A.13Object Properties  A.13 物体属性

In this task, an initial collection of objects with different properties (color, size, origin, smell, and material) are provided (e.g., a extra-small blue Canadian jar made of glass and with a smell of rose). Then, the collection goes through several updates corresponding to adding, removing or editing some of the objects. The updates are explained in the prompt and the models require a full grasp of the object properties to identify what changes to the collection must be made for each update. A simple example of an update is as follows:  
在此任务中，首先会提供一组具有不同属性（颜色、尺寸、产地、气味和材质）的物体（例如：一个由玻璃制成、带有玫瑰香味、产自加拿大的特小号蓝色罐子）。随后，该集合会经历若干次更新，对应着添加、移除或编辑某些物体。更新内容会在提示中说明，模型需要完全理解物体的属性，才能识别出每次更新必须对集合做出哪些更改。一个简单的更新示例如下：

For the above update, one has to find which color has been removed by comparing the new colors with the object colors in the previous collection, and then update the collection accordingly. The set of updates that the collection goes through in each of the examples are randomly selected from a large set of possible changes. At the end, a question is asked about the final collection. The question is either an _either_ question in which we ask how many items in the final collection have property 1 or property 2, … (e.g., how many items are either blue or small), or a _neither_ question in which we ask how many items neither have property 1 nor property 2, … (e.g., how many items are not blue and are not small).  
对于上述更新，需要通过比较新颜色与先前集合中的物体颜色，找出被移除的颜色，并相应更新集合。每个示例中集合所经历的一系列更新都是从大量可能的变化中随机选取的。最后，会提出一个关于最终集合的问题。问题要么是“或”问题，询问最终集合中有多少物品具有属性 1 或属性 2 等（例如，有多少物品是蓝色或小的），要么是“非”问题，询问有多少物品既不具有属性 1 也不具有属性 2 等（例如，有多少物品不是蓝色且不是小的）。

One of the updates, in particular, is a trick update. It says one of the objects of property X has been lost, but does not say which one. For example it says: I lost one of the blue objects without specifying which blue object. This update is made in a way that the final number is the same regardless of which object was lost. However, we observe that many of the models get confused with this update and assume that the final count cannot be computed since we do not know which item was lost. Specifically, o3-mini (high) says the problem cannot be solved in 8% of such cases, Gemini 2.0 Flash in 93.5% of the cases, and GPT4o in 96.5% of the cases.  
其中一项更新特别具有迷惑性。它声称属性 X 中的某个对象已丢失，但未指明具体是哪一个。例如，它会说：我丢失了一个蓝色物体，却不具体说明是哪个蓝色物体。这种更新方式使得无论丢失哪个物体，最终数量都保持不变。然而，我们观察到许多模型对此类更新感到困惑，认为由于不知道具体丢失了哪个物品，最终数量无法计算。具体来说，o3-mini（高精度版）在 8%的此类情况下表示问题无法解决，Gemini 2.0 Flash 在 93.5%的情况下如此，而 GPT4o 则在 96.5%的情况下持相同观点。

|   |   |   |   |   |   |
|---|---|---|---|---|---|
|Models  模型|Gemini 2.0 Flash-Lite  双子座 2.0 闪亮轻量版|Gemini 2.0 Flash  双子座 2.0 闪存版|GPT4o|DeepSeek R1|o3-mini (high)  o3-mini（高）|
|Over-count %  多计数百分比|53.0|50.5|17.5|6.0|1.5|
|Under-count %  少计数百分比|43.0|38.5|66.5|15.5|8.5|

Table 8:Percentage of problems from the Object Counting task where the models over-counted or under-counted.  
表 8：在物体计数任务中，模型多计数或少计数的题目所占百分比。

### A.14Object Counting  A.14 对象计数

Given a long list of objects that a person has, the model has to count the number of items of a certain type. For examples, the items might belong to classes (fruits, cell phones, cars) and the goal may be to count the total number of cell phones that the person has. We consider two types of questions: 1- counting the sum of the number of items belonging to two different classes, and 2- finding the absolute difference of the number of items belonging to two different classes. To add to the difficulty of the task, some irrelevant information, including the number of the same items that other people have, are added to the input context so the problem becomes one of finding multiple needles in a haystack.  
给定一份个人拥有的物品长列表，模型需要统计特定类型的物品数量。例如，物品可能属于不同类别（水果、手机、汽车），目标可能是计算此人拥有的手机总数。我们考虑两类问题：1-统计属于两个不同类别的物品数量总和；2-计算属于两个不同类别的物品数量绝对差值。为增加任务难度，输入上下文中会添加一些无关信息（包括其他人拥有的同类物品数量），使问题转化为"草堆寻针"式的多重检索挑战。

In Table [8](https://arxiv.org/html/2502.19187v2#A1.T8 "Table 8 ‣ A.13 Object Properties ‣ Appendix A Detailed Description of the Tasks and Task-Specific Insights from Experiments ‣ BIG-Bench Extra Hard"), we report the percentage of cases where each of the models either over-counted the number of objects or under-counted, for the subset where the sum of two sets must be reported. Interestingly, we observe a that different models have different failure modes on this task. The Gemini models tend to mostly over-count when they are wrong, whereas GPT4o, DeepSeek R1 and o3-mini tend to under-count when they are wrong.  
表 8 展示了各模型在需要报告两个集合总和的任务子集中，出现多计或少计错误的案例百分比。有趣的是，我们观察到不同模型在此任务上呈现不同的失败模式：Gemini 系列模型出错时倾向于多计，而 GPT4o、DeepSeek R1 和 o3-mini 模型出错时则倾向于少计。

### A.15SARC Triples  A.15SARC 三元组

SARC (Self-Annotated Corpus for Sarcasm) (Khodak et al., [2017](https://arxiv.org/html/2502.19187v2#bib.bib22)) is a large dataset of sarcasm responses mined from the Reddit social media / forum platform. Many Reddit users end a post or reply with the token “/s” when they have intended the preceding text to be interpreted sarcastically or satirically. This allowed positive examples of user-intended sarcasm to be mined.  
SARC（自我标注讽刺语料库）（Khodak 等人，2017）是一个从 Reddit 社交媒体/论坛平台挖掘的大型讽刺回应数据集。许多 Reddit 用户在帖子或回复的结尾使用标记“/s”，以表示他们希望前面的文本被解释为讽刺或讽刺性的。这使得能够挖掘出用户意图讽刺的正面示例。

Forking off the SARC dataset, we construct a challenging task for LLMs that requires reading three independent examples from SARC, and classifying each into binary label, where a positive label indicates sarcasm. The SARC authors created a balanced test set with 64,666 examples. Many of these examples can only be understood with an image or an article link that accompanied the original post or reply. On the other hand, some examples, usually with longer textual content, can be understood on their own. We design our derived benchmark to consist mainly of the latter type. To achieve this, we filter out examples with either (1) less than 100 characters or (2) without a reply, resulting in 679 examples from the original test set, with 48.4% positive label rate. We sample (uniformly-at-random) 600 examples from this set, group them (uniformly-at-random) into groups of three, and pass the text of each 3-tuple of post, reply pair to the following prompt:  
基于 SARC 数据集，我们构建了一项对 LLMs 具有挑战性的任务，要求模型阅读 SARC 中的三个独立示例，并将每个示例分类为二元标签，其中正标签表示讽刺。SARC 作者创建了一个包含 64,666 个示例的平衡测试集。其中许多示例需要结合原始帖子或回复所附带的图片或文章链接才能理解。另一方面，部分示例（通常文本内容较长）可以独立理解。我们设计的衍生基准主要包含后一种类型。为实现这一点，我们过滤掉以下两类示例：(1) 字符数少于 100 个，或(2) 没有回复内容，最终从原始测试集中得到 679 个示例，其中正标签占比 48.4%。我们从该集合中（均匀随机）抽取 600 个示例，将其（均匀随机）分成三人一组，并将每组三个帖文-回复对的文本输入以下提示模板：

### A.16Shuffled Objects  A.16 乱序物体

The original task in BBH is as follows: there are N people each assigned to an object/person (e.g., a dance partner, a book, a color, etc.). For example, Alice has a green book, Bob has a red book, etc. Then, there are multiple switch operations where pairs of people switch together what they are assigned to (e.g., Alice and Bob switch their books). At the end, one needs to predict the object/person assigned to one of the N people (e.g., at the end, what color is the book that Bob has?).  
BBH 中的原始任务如下：有 N 个人，每个人被分配到一个物体/人（例如，舞伴、书籍、颜色等）。例如，爱丽丝有一本绿色的书，鲍勃有一本红色的书，等等。然后，进行多次交换操作，其中成对的人一起交换他们被分配到的物体/人（例如，爱丽丝和鲍勃交换他们的书）。最后，需要预测 N 个人中某个人被分配到的物体/人（例如，最后，鲍勃的书是什么颜色？）。

We created two variants of this problem. In the first variant, we keep everything the same except that we add switch actions that have no effect. For example, we add Then, Person1 and Person2 switch their books. Then, Person2 and Person1 switch their books. We add many of these no-effect operations so that the problem becomes a long-context reasoning problem similar to the approach in Vodrahalli et al. ([2024](https://arxiv.org/html/2502.19187v2#bib.bib54)).  
我们创建了这个问题的两个变体。在第一个变体中，我们保持一切不变，只是添加了没有效果的交换动作。例如，我们添加：然后，人物 1 和人物 2 交换他们的书。接着，人物 2 和人物 1 交换他们的书。我们添加了许多这种没有效果的操作，使得问题变成了一个长上下文推理问题，类似于 Vodrahalli 等人（2024）的方法。

The second variant extends the first variant, in which we assign names to some of the switch actions as they occur and use those names later. For example, the first time Person1 switches with Person2 occurs, we replace the text with Person1 switches with Person2 (let’s call this Action K), and the next time the same switch happens, with some probability we replace the text with action K repeats. Given the long-context nature of the problem, the model requires to have the ability to remember information from many steps ago to be able to identify what that action corresponded to.  
第二种变体扩展了第一种变体，其中我们为某些切换动作发生时分配名称，并在后续使用这些名称。例如，当 Person1 与 Person2 首次发生切换时，我们将文本替换为“Person1 与 Person2 切换（我们称之为动作 K）”，而当下次相同的切换发生时，我们以一定概率将文本替换为“动作 K 重复”。鉴于问题的长上下文特性，模型需要具备记住多步之前信息的能力，以便能够识别该动作对应的是什么。

A naive approach to the problem in these tasks is to look at the switch operations one by one and keep updating the object/person assigned to each of the N people. This, however, will require track keeping over a very large number of operations. While reasoning-specialized models might still be able to do this thanks to their long outputs, this may be less feasible for the general-purpose models, and it is not the optimal solution to the problem. A more clever approach to the problem is to first identify all the operations that cancel each other out, and then do the track keeping only over the few operations that do not cancel.  
在这些任务中，一种天真的方法是逐个查看交换操作，并持续更新分配给 N 个人的对象/人员。然而，这需要在大量操作中保持跟踪。虽然专门用于推理的模型可能由于其长输出能力仍能完成此任务，但对于通用模型来说可能不太可行，而且这也不是问题的最优解。更巧妙的方法是首先识别出所有相互抵消的操作，然后仅对少数未抵消的操作进行跟踪。

Looking at some model traces, we observe that the models typically adopt the non-optimal approach of updating the state after each switch, thus running out of output tokens in some cases. For example, Gemini 2.0 Flash runs out of output tokens for 25% of the problems. We also observe a second failure case where, if the question asks about the person/object assigned to Person P at the end, the model assumes only switches involving Person P are important and other switches are irrelevant. This is, however, not True. To understand why, suppose "A" is assigned to "a", "B" is assigned to "b", and "C" is assigned to "c". Then "A" and "B" switch and then "B" and "C" switch, and then we want to know what "C" is assigned to. If we only consider the switches involving "C", then we may predict the correct answer to be "b" whereas the correct answer in this case is "a".  
通过观察一些模型追踪记录，我们发现模型通常采用非最优策略，即在每次交换后更新状态，这导致在某些情况下耗尽输出令牌。例如，Gemini 2.0 Flash 在 25%的问题中会出现输出令牌耗尽的情况。我们还观察到第二种失败情况：当问题询问最终分配给人物 P 的人或对象时，模型会假设只有涉及人物 P 的交换是重要的，而其他交换无关紧要。然而，这种假设并不正确。为了理解原因，假设"A"分配给"a"，"B"分配给"b"，"C"分配给"c"。接着"A"和"B"交换，然后"B"和"C"交换，此时若想知道"C"被分配给了什么。如果只考虑涉及"C"的交换，我们可能会预测正确答案为"b"，而此案例中的正确答案实际应为"a"。

### A.17Spatial Reasoning  A.17 空间推理

This task is mainly based on the problems in SpacialLLMEval (Yamada et al., [2023](https://arxiv.org/html/2502.19187v2#bib.bib62)). The problems describe a geometric construct composed of vertices and edges. At each vertex, there is a unique object. An agent starts from one of the vertices, moves along the edges and observes the objects at several vertices, and then after moving for several steps along the edges, the job of the model is to determine what object is at the final vertex where the agent stops.  
本任务主要基于 SpacialLLMEval（Yamada 等人，2023）中的问题。这些问题描述了一个由顶点和边构成的几何结构。每个顶点处都有一个独特的物体。智能体从其中一个顶点出发，沿着边移动并观察多个顶点处的物体，在沿着边移动若干步后，模型的任务是确定智能体最终停留的顶点处是什么物体。

We sampled from the hexagonal, circular, and rhombus constructs of SpacialLLMEval. We also created similar constructs with tree structure, triangular and diamond shapes and increased the difficulty compared to the problems in SpacialLLMEval by increasing the number of hops of reasoning (corresponding to the number of moves of the agent). Moreover, while the original problems and the aforementioned problems we created mainly require keeping track of the state after each move, we also create some variants of the problem where we provide multiple paths that intersect at some vertex, thus requiring backward reasoning from the intersection point to identify the position of the previous objects. As an example, consider the problem below:  
我们从 SpacialLLMEval 的六边形、圆形和菱形结构中进行了采样。此外，我们还创建了具有树状结构、三角形和菱形形状的类似结构，并通过增加推理的跳数（对应智能体的移动次数）来提高难度，相比 SpacialLLMEval 中的问题更具挑战性。同时，虽然原始问题和我们创建的上述问题主要需要跟踪每次移动后的状态，但我们也创建了一些问题的变体，其中提供了在某个顶点相交的多条路径，因此需要从交点进行反向推理来确定先前对象的位置。以下是一个示例问题：

For the first path (up until the first random jump), we know where the path starts and we can use that along with the following moves to determine which object is where. Then, a random jump is made to a vertex V but it is not specified which vertex it is. However, we observe that after a number of moves, the agent sees the _shampoo_ again so it can reason backward from this point to figure out which vertex it has been at in the previous steps. These information can also be used to determine the vertex V which must then be used to solve the problem when the second jump to V is made.  
对于第一条路径（直到第一次随机跳跃之前），我们知道路径的起点，并可以利用这一点以及后续的移动来确定各个物体的位置。接着，发生了一次随机跳跃，跳转到了某个顶点 V，但具体是哪个顶点并未说明。然而，我们观察到经过若干次移动后，智能体再次看到了洗发水，因此可以从这一点反向推理，推断出在前几步中它位于哪个顶点。这些信息也可用于确定顶点 V，而该顶点必须在第二次跳跃到 V 时用于解决问题。

We find that the problems involving backward reasoning are more challenging for the models. Specifically, we find that o3-mini (high) gives an accuracy of 58.8% on the forward-only problems and 19.2% on the backward problems and DeepSeek R1 gives an accuracy of 48.6% on the forward-only problems and 3.8% on the backward problems.  
我们发现涉及逆向推理的问题对模型更具挑战性。具体而言，o3-mini（高配版）在纯正向问题上的准确率为 58.8%，在逆向问题上为 19.2%；而 DeepSeek R1 在纯正向问题上的准确率为 48.6%，在逆向问题上仅为 3.8%。

### A.18SportQA  A.18 体育问答

SportQA (Xia et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib60)) is a challenging sports understanding dataset designed to test rule-based and strategic reasoning capabilities in LLMs beyond surface-level sports knowledge. It consists of three levels (Level 1 to Level 3) with increasing difficulty. In this work, we focus on Level 3 questions, which are curated by coaches and student athletes across six sports: soccer, basketball, volleyball, tennis, table tennis, and American football. We sub-sample 200 multi-hop reasoning questions and discard single-hop questions from the Level 3 set. Overall, these questions challenge LLMs to reason about fine-grained sports rules (e.g., penalty assessment and tactical choices), which expert student athletes can answer with near-perfect accuracy (Yang et al., [2024b](https://arxiv.org/html/2502.19187v2#bib.bib64)).  
SportQA（Xia 等人，2024 年）是一个具有挑战性的体育理解数据集，旨在测试 LLMs 超越表层体育知识的基于规则和战略推理能力。它包含三个难度递增的级别（从第 1 级到第 3 级）。在本研究中，我们专注于第 3 级问题，这些问题由教练和学生运动员在六项运动中共同策划：足球、篮球、排球、网球、乒乓球和美式橄榄球。我们从第 3 级数据集中抽取了 200 个多跳推理问题，并剔除了单跳问题。总体而言，这些问题挑战 LLMs 对细粒度体育规则（例如，判罚评估和战术选择）进行推理，而专业学生运动员能以近乎完美的准确率回答这些问题（Yang 等人，2024b 年）。

The questions we selected from SportQA have a compositional nature, in that a main question and some sub-questions are provided and the model has to answer all of them correctly for its answer to be considered correct. We add some instructions at the end of the questions so the models can answer them zero-shot in the format that we want. The questions are in the following format:  
我们从 SportQA 中选取的问题具有组合性质，即提供一个主要问题和若干子问题，模型必须正确回答所有问题，其答案才能被视为正确。我们在问题末尾添加了一些指令，以便模型能够以我们期望的格式进行零样本回答。问题的格式如下：

### A.19Temporal Sequences  A.19 时间序列

In this task, the calendar schedules of a few people is provided for an entire week. The blocked times for the calendar of each person is sampled randomly, and is provided as text either by giving the times of the day when it is blocked or giving the times of the day when it is free. The goal is to find: 1- the longest meeting that can be scheduled for them, and 2- the number of possibilities for such a meeting. These people may also have some constraints or we might have some information about them that has to be taken into account for meeting scheduling. Examples include: being in a different timezone than the other participants, needing some free time before/after the meeting, being flexible to miss a portion of the meeting, requiring some free time for lunch, only being able to attend meetings of up to a certain length, being willing to free up some specific parts of the day if needed, etc.  
在此任务中，提供了几个人一整周的日历安排。每个人的日历中被占用的时间段是随机抽取的，并以文本形式提供，要么给出一天中被占用的时间，要么给出一天中空闲的时间。目标是找出：1- 可以为他们安排的最长会议时长，以及 2- 此类会议的可能性数量。这些人可能还有一些限制条件，或者我们可能有一些关于他们的信息，需要在安排会议时加以考虑。例如：与其他参与者处于不同的时区、会议前后需要一些空闲时间、可以灵活地错过会议的一部分、需要一些午餐时间、只能参加特定时长的会议、愿意在必要时腾出一天中的某些特定时间段等。

The model predictions are considered correct if they predict both values (i.e. the longest time and the number of possibilities for a meeting of that length) correctly. We observe that both of these add to the difficulty of the problem. For example, o3-mini (high) has an overall accuracy of 68.5% on this problem, but if we only asked for the longest meeting time, then the accuracy will jump to 78%. The same is true for Gemini 2.0 Flash and Flash-Lite where their accuracy for the overall task is respectively 0.5% and 1.0%, but if we had asked only for the longest meeting time then their accuracy will jump to 5% and 7% respectively.  
若模型能同时正确预测两个数值（即最长会议时长及该时长对应的会议安排可能性数量），则视为预测正确。我们观察到这两个要求共同增加了问题的难度。例如，o3-mini（高配版）在此问题上的整体准确率为 68.5%，但若仅询问最长会议时长，准确率将跃升至 78%。Gemini 2.0 Flash 与 Flash-Lite 模型同样如此：它们在完整任务中的准确率分别为 0.5%和 1.0%，但若仅询问最长会议时长，准确率将分别跃升至 5%和 7%。

### A.20Time Arithmetic  A.20 时间算术

This task is based on the time arithmetic subset of the Test of Time (ToT) benchmark (Fatemi et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib9)). The original subset contains various questions about understanding, computations over, comparisons, and conversions of dates and times. There are also trick questions which may require extra thinking. The dataset also contains some scheduling problems, but we removed that subset given that we have an entire task (Temporal Sequence) dedicated to it.  
本任务基于时间测试基准的时间算术子集（Fatemi 等人，2024 年）。原始子集包含关于日期和时间理解、计算、比较和转换的各种问题。其中还包含一些可能需要额外思考的陷阱问题。该数据集也包含一些调度问题，但由于我们已有专门处理此类问题的完整任务（时间序列），因此移除了该子集。

Following Hosseini et al. ([2024](https://arxiv.org/html/2502.19187v2#bib.bib17)), we created a compositional version of the ToT Time Arithmetic dataset as follows. Let Q1 and Q2 be two questions from the original dataset, where the answer to the Q1 is A1 (A1 being a number) and let A2 be a number that is used in Q2. Then, we create a compositional question as follows:  
遵循 Hosseini 等人（2024 年）的方法，我们按以下方式创建了时间测试时间算术数据集的组合版本。设 Q1 和 Q2 为原始数据集中的两个问题，其中 Q1 的答案是 A1（A1 为数字），A2 为 Q2 中使用的数字。随后我们按以下方式创建组合问题：

In some cases, the answer to a question might contain multiple numbers, e.g. a date with three numbers. In those cases, we assign these values to variables X, Y, and Z and use them in the later questions.  
在某些情况下，问题的答案可能包含多个数字，例如包含三个数字的日期。在这些情况下，我们将这些值分配给变量 X、Y 和 Z，并在后续问题中使用它们。

### A.21Web of Lies  A.21 谎言之网

In this task, whether a specific person P1 tells the truth of lies is provided as input. Then, for other people, it is specified what they say about the truth value of some other person. This forms a chain-like structure that can be started from P1 and continued to find whether each of the people tells the truth or lies.  
在此任务中，特定人物 P1 是否说真话或撒谎作为输入提供。接着，对于其他人，会指定他们关于其他人真实性的陈述。这形成了一个链式结构，可以从 P1 开始，并继续推断每个人是否说真话或撒谎。

We used two different variants for this task. The first variant comes from the _web of lies V2_ from LiveBench White et al. ([2024](https://arxiv.org/html/2502.19187v2#bib.bib59)). In this variant, complexity has been added to the task by specifying where each person is, and then having sentences such as _The person at the cafe says the person at the zoo lies_. The second version is created by us. In this version, we add cyclic cases whose truth value remains unknown, but one can still infer something about them and continue the chain. For example, consider a cyclic case such as _Person1 says Person2 tells the truth. Person2 says Person1 tells the truth._ In this case, we cannot determine whether Person1 or Person2 tell the truth or lie (so their truthfulness remains unknown). However, if we have another sentence _Person3 says either both Person1 and Person2 lie or both tell the truth_, we can determine that Person3 tells the truth. In both variants of the problems, we ask about the truthfulness of three of the people in the chain, so the random chance performance for the LiveBench subset is 1/8 since the truthfulness of each of the three people can be either yes or no, and 1/27 for our new set given that the values can also be unknown.  
我们为此任务使用了两种不同的变体。第一种变体来自 LiveBench White 等人（2024）的“谎言网络 V2”。在此变体中，通过指定每个人的位置来增加任务的复杂性，然后使用诸如“咖啡馆里的人说动物园里的人说谎”这样的句子。第二种版本由我们创建。在此版本中，我们添加了循环案例，其真值仍然未知，但人们仍然可以推断出一些信息并继续推理链。例如，考虑一个循环案例，如“人物 1 说人物 2 说真话。人物 2 说人物 1 说真话”。在这种情况下，我们无法确定人物 1 或人物 2 是说真话还是说谎（因此他们的真实性仍然未知）。然而，如果我们有另一句话“人物 3 说要么人物 1 和人物 2 都说谎，要么都说真话”，我们可以确定人物 3 说的是真话。在这两种问题变体中，我们询问推理链中三个人的真实性，因此 LiveBench 子集的随机机会表现是 1/8 ，因为这三个人的真实性可以是“是”或“否”，而我们新集合的随机机会表现是 1/27 ，因为值也可以是“未知”。

We observe that the first subset is easier than the second subset, so we included only 40 examples of subset one and 160 of subset 2. Specifically, o3-mini (high) gives an accuracy of 100% on subset one and Gemini 2.0 Flash gives an accuracy of 77.5%, whereas on the second subset the two models give an accuracy of 28.8% and 3.8%. We still keep the first subset despite the high performance of the o3-mini model so it can be used to distinguish among smaller, general-purpose models.  
我们观察到第一个子集比第二个子集更容易，因此我们只纳入了子集一的 40 个示例和子集二的 160 个示例。具体来说，o3-mini（高配版）在子集一上的准确率达到 100%，而 Gemini 2.0 Flash 的准确率为 77.5%；相比之下，在第二个子集上，这两个模型的准确率分别为 28.8%和 3.8%。尽管 o3-mini 模型在第一个子集上表现出色，我们仍保留该子集，以便用于区分较小规模的通用模型。

For the new set we created, we always ask about the truthfulness of one of the people at the end of the chain, and another person at an earlier position in the chain (but still far off in the chain). Conceptually, one would expect that if a model has made a mistake for the person at an earlier position in the chain, then the chances of making a mistake for the person at the end of the chain must be higher. We verified whether this is the case for our models. For o3-mini, we observe that the accuracy for both cases is 41.2%, for Gemini 2.0 Flash it is 30% for the earlier person and 27.5% for the last person, and for Gemini 2.0 Flash-Lite it is 25.6% for the earlier person and 21.2% for the last person, all showing this effect. GPT4o, however, is surprisingly behaving the opposite, having an accuracy of 19.4% for the earlier person and 25% for the last person.  
在我们新创建的数据集中，我们总是询问链条末端某人的真实性，以及链条中较早位置（但仍处于链条较远端）的另一人的真实性。从概念上讲，人们会预期，如果模型对链条中较早位置的人做出了错误判断，那么对链条末端的人做出错误判断的概率必然会更高。我们验证了我们的模型是否确实如此。对于 o3-mini，我们观察到两种情况下的准确率均为 41.2%；对于 Gemini 2.0 Flash，较早位置的人的准确率为 30%，最后一个人的准确率为 27.5%；对于 Gemini 2.0 Flash-Lite，较早位置的人的准确率为 25.6%，最后一个人的准确率为 21.2%，所有这些模型都显示了这种效应。然而，GPT4o 的表现却出人意料地相反，较早位置的人的准确率为 19.4%，最后一个人的准确率为 25%。

### A.22Word Sorting  A.22 单词排序

The Word Sorting task is split into 2 sub-tasks.  
词语排序任务被划分为两个子任务。

The first sub-task is from the BIG-Bench Mistake dataset (Tyen et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib53)). This task involves finding the first mistake in an existing chain-of-thought sequence, used to answer a Word Sorting question in the original BBH dataset. In each example, the target answer is either the number where the first mistake occurred, or that there are no mistakes in the CoT sequence. These CoT sequences are generated by prompting PaLM 2 Unicorn (Anil et al., [2023](https://arxiv.org/html/2502.19187v2#bib.bib2)) on the original BBH dataset at temperature = 0. The newline is used as a stop token so that each intermediate step can be prepended with ‘Thought 1: ’, ‘Thought 2: ’, etc. Further information on the prompting and generation process can be found in Tyen et al. ([2024](https://arxiv.org/html/2502.19187v2#bib.bib53)).  
第一个子任务源自 BIG-Bench 错误数据集（Tyen 等人，2024）。该任务需要在现有的思维链序列中找出第一个错误，该序列原本用于回答原始 BBH 数据集中的词语排序问题。每个示例的目标答案要么是首次出现错误的步骤编号，要么表明思维链序列中不存在错误。这些思维链序列是通过在原始 BBH 数据集上以温度参数设为 0 的条件提示 PaLM 2 Unicorn 模型（Anil 等人，2023）生成的。换行符被用作停止标记，使得每个中间步骤都能被冠以“思考 1：”、“思考 2：”等前缀。关于提示和生成过程的更多详细信息可参阅 Tyen 等人（2024）的研究。

The second sub-task is sorting a list of words given a new alphabet order (examples include: an alphabet order that is the same as English but two letters are swapped in the order, an alphabet order that is the same as English but one/two letters are moved to the beginning/end of the order, or a completely new order). This task requires going against a strong prior and sorting words in a non-typical way. We observe an interesting failure mode for this task where some models understand the new alphabet order correctly but keep sorting the words based on the original English order. As an example, consider the following question:  
第二个子任务是根据新的字母顺序对单词列表进行排序（例如：字母顺序与英语相同但有两个字母在顺序中互换，字母顺序与英语相同但有一个/两个字母被移到顺序的开头/结尾，或者一个全新的顺序）。这项任务需要违背强烈的先验知识，以非典型的方式对单词进行排序。我们观察到这项任务有一个有趣的失败模式，即一些模型正确理解了新的字母顺序，但仍然按照原始英语顺序对单词进行排序。例如，考虑以下问题：

Gemini 2.0 Flash provides the following response:  
Gemini 2.0 Flash 提供了以下回应：

While the model provides the correct new alphabet, we see that the final answer is sorted based on the original order (which agrees better with model’s prior), and not based on the new order.  
模型虽然提供了正确的新字母表，但我们发现最终答案是根据原始顺序（这更符合模型的先验知识）而非新顺序进行排序的。

|   |   |   |   |   |
|---|---|---|---|---|
|Puzzle Size / Models  谜题尺寸 / 模型|Gemini 2.0 Flash-Lite  双子座 2.0 闪亮轻量版|Gemini 2.0 Flash  双子座 2.0 闪存版|GPT4o|o3-mini (high)  o3-mini（高）|
|5 x 5 (with distractors)  <br>5 x 5（含干扰项）|37.5|60.0|37.5|90.0|
|6 x 6 (with distractors)  <br>6 x 6（含干扰项）|38.9|33.3|30.6|58.3|
|7 x 7 (with distractors)  <br>7 x 7（含干扰项）|36.5|36.5|37.8|55.4|
|8 x 8 (without distractors)  <br>8 x 8（无干扰项）|16.0|52.0|20.0|74.0|

Table 9:Accuracy break-down of the model performances on the Zebra Puzzles task by puzzle size.  
表 9：按谜题大小划分的模型在斑马谜题任务上的准确率细分。

### A.23Zebra Puzzles  A.23 斑马谜题

Zebra puzzles, also known as Einstein puzzles, are verbal descriptions of entities and properties that partially populate a grid linking entities to their properties (Shah et al., [2024](https://arxiv.org/html/2502.19187v2#bib.bib43)). The description may also include constraints on these properties, such that it is possible to deduce the other entity-property links. Following the approach in Shah et al. ([2024](https://arxiv.org/html/2502.19187v2#bib.bib43)), we generate square-grid Zebra puzzles of size 5x5, 6x6, 7x7, and 8x8. We add distracting clues to puzzles of size 5, 6, and 7 to make them more challenging, but do not add them to puzzles of size 8 to avoid keeping the context size too large. To simplify evaluation, the questions ask for the position of one of the n people in the n x n puzzles, so the random chance performance for a n x n puzzle is 1/n.  
斑马谜题，又称爱因斯坦谜题，是对实体及其属性的文字描述，这些描述部分填充了一个将实体与其属性联系起来的网格（Shah 等人，2024）。描述中可能还包括对这些属性的约束条件，从而可以推断出其他实体与属性之间的联系。遵循 Shah 等人（2024）的方法，我们生成了大小为 5x5、6x6、7x7 和 8x8 的方形网格斑马谜题。我们在大小为 5、6 和 7 的谜题中添加了干扰线索以增加挑战性，但未在大小为 8 的谜题中添加，以避免上下文规模过大。为简化评估，问题要求找出 n x n 谜题中 n 个人的位置之一，因此 n x n 谜题的随机猜测性能为 1/n 。

Looking at the performance for the top performing models in Table [9](https://arxiv.org/html/2502.19187v2#A1.T9 "Table 9 ‣ A.22 Word Sorting ‣ Appendix A Detailed Description of the Tasks and Task-Specific Insights from Experiments ‣ BIG-Bench Extra Hard"), we notice two interesting patterns. Firstly, while the random chance performance is lower for larger puzzles, we see that increasing the puzzle sizes does not significantly lower the model performances in some cases. This is especially true when going from puzzles of size 6 to 7. Secondly, we observe that the top-2 models (Gemini 2.0 Flash and o3-mini high) perform significantly better on the 8x8 puzzles that have no distracting clues compared to the smaller puzzles of size 7x7 or 6x6 that do have distracting clues. This hints at a possible failure mode for frontier models: they seem to get confused in presence of distractors and underperform. This might be in part due to the fact that models might have already seen clean zebra puzzles and their solutions, but they may not have seen the variant with distracting clues, making the latter a case of out-of-distribution generalization.  
观察表 9 中表现最佳模型的性能，我们注意到两个有趣的现象。首先，虽然较大谜题的随机猜测正确率较低，但我们发现增加谜题尺寸在某些情况下并未显著降低模型表现——从 6 阶谜题过渡到 7 阶谜题时尤其明显。其次，我们观察到排名前两位的模型（Gemini 2.0 Flash 和 o3-mini high）在无干扰线索的 8x8 谜题上表现显著优于存在干扰线索的较小尺寸谜题（7x7 或 6x6）。这暗示了前沿模型可能存在一种失效模式：它们在干扰信息面前容易产生混淆，导致表现不佳。部分原因可能是模型已接触过标准斑马谜题及其解法，但可能未见过包含干扰线索的变体，使得后者成为分布外泛化的测试案例。

## Appendix BBBEH vs BBH Performance  
附录：BBEH 与 BBH 性能对比

To understand how much each task in BBEH has become harder compared to its counterpart in BBH, we evaluated Gemini 2.0 Flash on BBH and reported the results in Table [10](https://arxiv.org/html/2502.19187v2#A2.T10 "Table 10 ‣ Appendix B BBEH vs BBH Performance ‣ BIG-Bench Extra Hard"). For the fairness of the comparison, we ran the model in a zero-shot setting. However, we note that some of the tasks in BBH may become slightly ambiguous in a zero-shot setting given that it has been mostly developed for a few-shot evaluation. Nevertheless, we observe that on almost all the tasks, the difficulty level has significantly increased in BBEH. A notable exception is the DisambiguationQA task. Checking the responses from Gemini 2.0 Flash on the BBH version of the dataset, we observe that the model overly selects the ambiguous option, sometimes for potentially legit reasons. For example, for disambiguating the pronoun _they_ in the sentence _Alex told us that they could not meet_, the model responds that _They could refer to Alex or to some other group of people not explicitly mentioned. Therefore, the antecedent is ambiguous_. We also find that in several of the cases, simply changing the task description from _explain the antecedent of the pronoun […] or state that it is ambiguous_ to _try to disambiguate the antecedent of the pronoun given the context or state that it is ambiguous if it cannot be disambiguated_ makes the model pick the right choice.  
为理解 BBEH 中各项任务相较于 BBH 对应任务的难度提升程度，我们在 BBH 上评估了 Gemini 2.0 Flash 模型，并将结果呈现在表 10 中。为确保对比公平性，我们采用零样本设置运行模型。但需注意，由于 BBH 主要针对少样本评估设计，部分任务在零样本设置下可能产生轻微歧义。尽管如此，我们观察到在几乎所有任务上，BBEH 的难度水平均显著提升。一个值得注意的例外是消歧问答任务。通过检查 Gemini 2.0 Flash 在 BBH 版本数据集上的响应，我们发现该模型过度选择歧义选项，有时可能出于合理原因。例如，在消歧句子"Alex 告诉我们他们无法见面"中的代词"他们"时，模型回应称"他们可能指代 Alex，也可能指代未明确提及的其他人群体，因此先行词存在歧义"。 我们还发现，在多个案例中，仅将任务描述从“解释代词的先行词[…]或说明其存在歧义”改为“尝试根据上下文消除代词先行词的歧义，若无法消除则说明其存在歧义”，就能使模型做出正确选择。

|   |   |   |
|---|---|---|
|Task in BBEH ↓ / Accuracy on →  <br>BBEH 任务 ↓ / 在 → 上的准确率|Old task from BBH  <br>来自 BBH 的旧任务|New task in BBEH  <br>BBEH 中的新任务|
|BoardgameQA  棋盘游戏问答|88.0|42.5|
|Boolean Expressions  布尔表达式|97.6|27.0|
|Causal Understanding  因果理解|65.2|52.0|
|DisambiguationQA  消歧问答|42.0|48.3|
|Dyck Languages  戴克语言|65.2|14.0|
|Geometric Shapes  几何形状|73.6|35.0|
|Hyperbaton  超常语序|94.8|4.5|
|SARC Triples  SARC 三重任务|86.0|37.5|
|Linguini  意大利细面条|62.8|15.5|
|Movie Recommendation  电影推荐|66.4|59.5|
|Multistep Arithmetic  多步算术|99.6|9.5|
|NYCC|81.2|11.0|
|Object Properties  对象属性|96.8|1.5|
|Object Counting  物体计数|97.6|11.0|
|Shuffled Objects  乱序对象|100.0|9.0|
|Spatial Reasoning  空间推理|97.6|18.5|
|SportQA  体育问答|89.6|23.0|
|Buggy Tables  故障表格|98.6|3.5|
|Temporal Sequences  时间序列|98.8|0.5|
|Time Arithmetic  时间运算|92.0|48.0|
|Web of Lies  谎言网络|94.8|18.5|
|Word Sorting  单词排序|84.8|26.0|
|Zebra Puzzles  斑马谜题|87.6|44.5|
|BBEH|85.2|23.90|

Table 10:Performance of Gemini 2.0 Flash on BBEH and its counterpart task from BBH.  
表 10：Gemini 2.0 Flash 在 BBEH 及其对应任务 BBH 上的性能表现。

## Appendix CReproducibility  
附录 C 可复现性

For most of the models we tested in this work, we obtained the results through API calls. Specifically, for Gemini 2.0 and Gemma2 models, we used AI Studio, for GPT4o and o3-mini (high) we used the OpenAI API, and for DeepSeek R1 results we used the API from Together AI. For the LLama and Distill R1 Qwen results, whose parameters are available publicly, we obtained results by loading them on GPUs. This ensures reproducibility as other researchers can also follow the same approach and obtain our results.  
在本研究中，我们测试的大多数模型结果均通过 API 调用获得。具体而言，对于 Gemini 2.0 和 Gemma2 模型，我们使用了 AI Studio 平台；对于 GPT4o 和 o3-mini（高配版），我们调用了 OpenAI API；而 DeepSeek R1 的结果则通过 Together AI 的 API 获取。至于参数已公开的 LLama 和 Distill R1 Qwen 模型，我们通过在 GPU 上加载模型的方式获得结果。这种方法确保了结果的可复现性，其他研究者也可遵循相同流程复现我们的实验结果。

For all of our problems, we added the following suffix to the text of the question to encourage the model to produce the final answer in a format that we can easily extract it:  
针对我们所有的问题，我们在问题文本后添加了以下后缀，以鼓励模型以易于提取的格式生成最终答案：

We then extract the answer by splitting with the prefix and finding what comes next. We find that sometimes the models slightly deviate from the exact prefix we gave them, so we look for four prefixes in the answer until one of them is found: "The answer is: ", "The answer is ", "The final answer is: ", "The final answer is ". Once we extract the final answer, we apply some minimal cleaning as follows: 1- if the final answer is wrapped within the _boxed_, _text_, _texttt_ or _**_, we remove that and extract what is inside it. We notice that after producing the final answer, some models produce a "\n" and then some extra text. Therefore, we split the extracted final answer using "\n" and take the first element as the final answer. Then we lowercase both the final answer and the label determine correctness using a few simple rules: 1- if the two are identical, then we consider the final answer correct, 2- if the final answer is identical to the label up to removing single or double quotes or brackets from the beginning and end of it, we consider it to be correct, 3- the label for multi-choice questions is in (<LETTER>) format and we expect a similar final answer but if the final answer is only the letter without the parentheses, we consider it correct, and finally 4- for questions whose labels contain multiple elements separated by comma, if the label and final answer are the same up to replacing the spaces after the commas with blanks, then we consider the final answer to be correct.  
随后，我们通过按前缀分割并查找紧随其后的内容来提取答案。我们发现，模型有时会与我们提供的精确前缀略有偏差，因此我们会在答案中查找四种前缀，直到找到其中之一："答案是："、"答案是"、"最终答案是："、"最终答案是"。一旦提取出最终答案，我们会进行如下最小化清理：1- 如果最终答案被包裹在 boxed、text、texttt 或**中，我们会移除这些标记并提取其中的内容。我们注意到，在生成最终答案后，一些模型会产生一个"\n"以及一些额外文本。因此，我们使用"\n"分割提取的最终答案，并将第一个元素作为最终答案。 接着我们将最终答案和标签都转换为小写，并通过几条简单规则来判断正确性：1- 如果两者完全相同，则认为最终答案正确；2- 如果最终答案在去除首尾的单引号、双引号或括号后与标签一致，也视为正确；3- 对于多选题，标签格式为(<字母>)，我们期望最终答案格式类似，但如果最终答案仅包含字母而无括号，同样判定为正确；最后 4- 对于标签中包含由逗号分隔的多个元素的问题，如果标签和最终答案在将逗号后的空格替换为空白后相同，则认定最终答案正确。

  报告问题

  
由 L T E xml ![[LOGO]](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAAOCAYAAAD5YeaVAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wKExQZLWTEaOUAAAAddEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIFRoZSBHSU1Q72QlbgAAAdpJREFUKM9tkL+L2nAARz9fPZNCKFapUn8kyI0e4iRHSR1Kb8ng0lJw6FYHFwv2LwhOpcWxTjeUunYqOmqd6hEoRDhtDWdA8ApRYsSUCDHNt5ul13vz4w0vWCgUnnEc975arX6ORqN3VqtVZbfbTQC4uEHANM3jSqXymFI6yWazP2KxWAXAL9zCUa1Wy2tXVxheKA9YNoR8Pt+aTqe4FVVVvz05O6MBhqUIBGk8Hn8HAOVy+T+XLJfLS4ZhTiRJgqIoVBRFIoric47jPnmeB1mW/9rr9ZpSSn3Lsmir1fJZlqWlUonKsvwWwD8ymc/nXwVBeLjf7xEKhdBut9Hr9WgmkyGEkJwsy5eHG5vN5g0AKIoCAEgkEkin0wQAfN9/cXPdheu6P33fBwB4ngcAcByHJpPJl+fn54mD3Gg0NrquXxeLRQAAwzAYj8cwTZPwPH9/sVg8PXweDAauqqr2cDjEer1GJBLBZDJBs9mE4zjwfZ85lAGg2+06hmGgXq+j3+/DsixYlgVN03a9Xu8jgCNCyIegIAgx13Vfd7vdu+FweG8YRkjXdWy329+dTgeSJD3ieZ7RNO0VAXAPwDEAO5VKndi2fWrb9jWl9Esul6PZbDY9Go1OZ7PZ9z/lyuD3OozU2wAAAABJRU5ErkJggg==) 生成

##   
错误报告说明

  
我们正在持续改进论文的 HTML 版本，您的反馈有助于提升可访问性和移动端支持。要报告 HTML 中的错误以帮助我们改进转换和渲染效果，请选择以下任一方法：

-   
    点击“报告问题”按钮。
-   
    通过键盘打开报告反馈表单，使用“Ctrl + ?”。
-   
    选择文本，然后点击光标附近的“报告选中内容问题”按钮。

  
我们的团队已经识别出以下问题。感谢您花时间审阅并报告我们可能尚未发现的渲染错误。您的努力将帮助我们改进所有读者的 HTML 版本，因为残疾不应成为获取研究的障碍。感谢您持续支持倡导所有人的开放获取。

  
有空闲的开发周期吗？帮助支持 arXiv 的无障碍访问！我们的 LaTeXML 合作者维护了一个需要转换的软件包列表，并欢迎开发者的贡献。